<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */


	 protected $districs = [
	             ['Dhaka','ঢাকা'],
	             ['Faridpur','ফরিদপুর'],
	             ['Gazipur','গাজীপুর'],
	             ['Gopalganj','গোপালগঞ্জ'],
	             ['Jamalpur','জামালপুর'],
	             ['Kishoreganj','কিশোরগঞ্জ'],
	             ['Madaripur','মাদারীপুর'],
	             ['Manikganj','মানিকগঞ্জ'],
	             ['Munshiganj','মুন্সিগঞ্জ'],
	             ['Mymensingh','ময়মনসিং'],
	             ['Narayanganj','নারায়াণগঞ্জ'],
	             ['Narsingdi','নরসিংদী'],
	             ['Netrokona','নেত্রকোনা'],
	             ['Rajbari','রাজবাড়ি'],
	             ['Shariatpur','শরীয়তপুর'],
	             ['Sherpur','শেরপুর'],
	             ['Tangail','টাঙ্গাইল'],
	             ['Bogra','বগুড়া'],
	             ['Joypurhat','জয়পুরহাট'],
	             ['Naogaon','নওগাঁ'],
	             ['Natore','নাটোর'],
	             ['Nawabganj','নবাবগঞ্জ'],
	             ['Pabna','পাবনা'],
	             ['Rajshahi','রাজশাহী'],
	             ['Sirajgonj','সিরাজগঞ্জ'],
	             ['Dinajpur','দিনাজপুর'],
	             ['Gaibandha','গাইবান্ধা'],
	             ['Kurigram','কুড়িগ্রাম'],
	             ['Lalmonirhat','লালমনিরহাট'],
	             ['Nilphamari','নীলফামারী'],
	             ['Panchagarh','পঞ্চগড়'],
	             ['Rangpur','রংপুর'],
	             ['Thakurgaon','ঠাকুরগাঁও'],
	             ['Barguna','বরগুনা'],
	             ['Barisal','বরিশাল'],
	             ['Bhola','ভোলা'],
	             ['Jhalokati','ঝালকাঠি'],
	             ['Patuakhali','পটুয়াখালী'],
	             ['Pirojpur','পিরোজপুর'],
	             ['Bandarban','বান্দরবান'],
	             ['Brahmanbaria','ব্রাহ্মণবাড়িয়া'],
	             ['Chandpur','চাঁদপুর'],
	             ['Chittagong','চট্টগ্রাম'],
	             ['Comilla','কুমিল্লা'],
	             ['Cox\'s Bazar','কক্স বাজার'],
	             ['Feni','ফেনী'],
	             ['Khagrachari','খাগড়াছড়ি'],
	             ['Lakshmipur','লক্ষ্মীপুর'],
	             ['Noakhali','নোয়াখালী'],
	             ['Rangamati','রাঙ্গামাটি'],
	             ['Habiganj','হবিগঞ্জ'],
	             ['Maulvibazar','মৌলভীবাজার'],
	             ['Sunamganj','সুনামগঞ্জ'],
	             ['Sylhet','সিলেট'],
	             ['Bagerhat','বাগেরহাট'],
	             ['Chuadanga','চুয়াডাঙ্গা'],
	             ['Jessore','যশোর'],
	             ['Jhenaidah','ঝিনাইদহ'],
	             ['Khulna','খুলনা'],
	             ['Kushtia','কুষ্টিয়া'],
	             ['Magura','মাগুরা'],
	             ['Meherpur','মেহেরপুর'],
	             ['Narail','নড়াইল'],
	             ['Satkhira','সাতক্ষীরা'],
	         ];

			protected $places = [
							['Amtali-Amtali'],
							['Bamna-Bamna'],
							['Barguna Sadar-Barguna Sadar'],
							['Barguna Sadar-Nali Bandar'],
							['Betagi-Betagi'],
							['Betagi-Darul Ulam'],
							['Patharghata-Kakchira'],
							['Patharghata-Patharghata'],
							['Agailzhara-Agailzhara'],
							['Agailzhara-Gaila'],
							['Agailzhara-Paisarhat'],
							['Babuganj-Babuganj'],
							['Babuganj-Barishal Cadet'],
							['Babuganj-Chandpasha'],
							['Babuganj-Madhabpasha'],
							['Babuganj-Nizamuddin College'],
							['Babuganj-Rahamatpur'],
							['Babuganj-Thakur Mallik'],
							['Barajalia-Barajalia'],
							['Barajalia-Osman Manjil'],
							['Barishal Sadar-Barishal Sadar'],
							['Barishal Sadar-Bukhainagar'],
							['Barishal Sadar-Jaguarhat'],
							['Barishal Sadar-Kashipur'],
							['Barishal Sadar-Patang'],
							['Barishal Sadar-Saheberhat'],
							['Barishal Sadar-Sugandia'],
							['Gouranadi-Batajor'],
							['Gouranadi-Gouranadi'],
							['Gouranadi-Kashemabad'],
							['Gouranadi-Tarki Bandar'],
							['Mahendiganj-Langutia'],
							['Mahendiganj-Laskarpur'],
							['Mahendiganj-Mahendiganj'],
							['Mahendiganj-Nalgora'],
							['Mahendiganj-Ulania'],
							['Muladi-Charkalekhan'],
							['Muladi-Kazirchar'],
							['Muladi-Muladi'],
							['Sahebganj-Charamandi'],
							['Sahebganj-kalaskati'],
							['Sahebganj-Padri Shibpur'],
							['Sahebganj-Sahebganj'],
							['Sahebganj-Shialguni'],
							['Uzirpur-Dakuarhat'],
							['Uzirpur-Dhamura'],
							['Uzirpur-Jugirkanda'],
							['Uzirpur-Shikarpur'],
							['Uzirpur-Uzirpur'],
							['Bhola Sadar-Bhola Sadar'],
							['Bhola Sadar-Joynagar'],
							['Borhanuddin UPO-Borhanuddin UPO'],
							['Borhanuddin UPO-Mirzakalu'],
							['Charfashion-Charfashion'],
							['Charfashion-Dularhat'],
							['Charfashion-Keramatganj'],
							['Doulatkhan-Doulatkhan'],
							['Doulatkhan-Hajipur'],
							['Hajirhat-Hajirhat'],
							['Hatshoshiganj-Hatshoshiganj'],
							['Lalmohan UPO-Daurihat'],
							['Lalmohan UPO-Gazaria'],
							['Lalmohan UPO-Lalmohan UPO'],
							['Jhalokathi Sadar-Baukathi'],
							['Jhalokathi Sadar-Gabha'],
							['Jhalokathi Sadar-Jhalokathi Sadar'],
							['Jhalokathi Sadar-Nabagram'],
							['Jhalokathi Sadar-Shekherhat'],
							['Kathalia-Amua'],
							['Kathalia-Kathalia'],
							['Kathalia-Niamatee'],
							['Kathalia-Shoulajalia'],
							['Nalchhiti-Beerkathi'],
							['Nalchhiti-Nalchhiti'],
							['Rajapur-Rajapur'],
							['Bauphal-Bagabandar'],
							['Bauphal-Bauphal'],
							['Bauphal-Birpasha'],
							['Bauphal-Kalaia'],
							['Bauphal-Kalishari'],
							['Dashmina-Dashmina'],
							['Galachipa-Galachipa'],
							['Galachipa-Gazipur Bandar'],
							['Khepupara-Khepupara'],
							['Khepupara-Mahipur'],
							['Patuakhali Sadar-Dumkee'],
							['Patuakhali Sadar-Moukaran'],
							['Patuakhali Sadar-Patuakhali Sadar'],
							['Patuakhali Sadar-Rahimabad'],
							['Subidkhali-Subidkhali'],
							['Banaripara-Banaripara'],
							['Banaripara-Chakhar'],
							['Bhandaria-Bhandaria'],
							['Bhandaria-Dhaoa'],
							['Bhandaria-Kanudashkathi'],
							['kaukhali-Jolagati'],
							['kaukhali-Joykul'],
							['kaukhali-Kaukhali'],
							['kaukhali-Keundia'],
							['Mathbaria-Betmor Natun Hat'],
							['Mathbaria-Gulishakhali'],
							['Mathbaria-Halta'],
							['Mathbaria-Mathbaria'],
							['Mathbaria-Shilarganj'],
							['Mathbaria-Tiarkhali'],
							['Mathbaria-Tushkhali'],
							['Nazirpur-Nazirpur'],
							['Nazirpur-Sriramkathi'],
							['Pirojpur Sadar-Hularhat'],
							['Pirojpur Sadar-Parerhat'],
							['Pirojpur Sadar-Pirojpur Sadar'],
							['Swarupkathi-Darus Sunnat'],
							['Swarupkathi-Jalabari'],
							['Swarupkathi-Kaurikhara'],
							['Swarupkathi-Swarupkathi'],
							['Alikadam-Alikadam'],
							['Bandarban Sadar-Bandarban Sadar'],
							['Naikhong-Naikhong'],
							['Roanchhari-Roanchhari'],
							['Ruma-Ruma'],
							['Thanchi-Lama'],
							['Thanchi-Thanchi'],
							['Akhaura-Akhaura'],
							['Akhaura-Azampur'],
							['Akhaura-Gangasagar'],
							['Banchharampur-Banchharampur'],
							['Brahamanbaria Sadar-Ashuganj'],
							['Brahamanbaria Sadar-Ashuganj Share'],
							['Brahamanbaria Sadar-Brahamanbaria Sadar'],
							['Brahamanbaria Sadar-Poun'],
							['Brahamanbaria Sadar-Talshahar'],
							['Kasba-Chandidar'],
							['Kasba-Chargachh'],
							['Kasba-Gopinathpur'],
							['Kasba-Kasba'],
							['Kasba-Kuti'],
							['Nabinagar-Jibanganj'],
							['Nabinagar-Kaitala'],
							['Nabinagar-Laubfatehpur'],
							['Nabinagar-Nabinagar'],
							['Nabinagar-Rasullabad'],
							['Nabinagar-Ratanpur'],
							['Nabinagar-Salimganj'],
							['Nabinagar-Shahapur'],
							['Nabinagar-Shamgram'],
							['Nasirnagar-Fandauk'],
							['Nasirnagar-Nasirnagar'],
							['Sarail-Chandura'],
							['Sarail-Sarial'],
							['Sarail-Shahbajpur'],
							['Chandpur Sadar-Baburhat'],
							['Chandpur Sadar-Chandpur Sadar'],
							['Chandpur Sadar-Puranbazar'],
							['Chandpur Sadar-Sahatali'],
							['Faridganj-Chandra'],
							['Faridganj-Faridganj'],
							['Faridganj-Gridkaliandia'],
							['Faridganj-Islampur Shah Isain '],
							['Faridganj-Rampurbazar'],
							['Faridganj-Rupsha'],
							['Hajiganj-Bolakhal'],
							['Hajiganj-Hajiganj'],
							['Hayemchar-Gandamara'],
							['Hayemchar-Hayemchar'],
							['Kachua-Kachua'],
							['Kachua-Pak Shrirampur'],
							['Kachua-Rahima Nagar'],
							['Kachua-Shachar'],
							['Matlobganj-Kalipur'],
							['Matlobganj-Matlobganj'],
							['Matlobganj-Mohanpur'],
							['Shahrasti-Chotoshi'],
							['Shahrasti-Islamia Madrasha'],
							['Shahrasti-Khilabazar'],
							['Shahrasti-Pashchim Kherihar Al'],
							['Shahrasti-Shahrasti'],
							['Anawara-Anowara'],
							['Anawara-Battali'],
							['Anawara-Paroikora'],
							['Boalkhali-Boalkhali'],
							['Boalkhali-Charandwip'],
							['Boalkhali-Iqbal Park'],
							['Boalkhali-Kadurkhal'],
							['Boalkhali-Kanungopara'],
							['Boalkhali-Sakpura'],
							['Boalkhali-Saroatoli'],
							['Chittagong Sadar-Al- Amin Baria Madra'],
							['Chittagong Sadar-Amin Jute Mills'],
							['Chittagong Sadar-Anandabazar'],
							['Chittagong Sadar-Bayezid Bostami'],
							['Chittagong Sadar-Chandgaon'],
							['Chittagong Sadar-Chawkbazar'],
							['Chittagong Sadar-Chitt. Cantonment'],
							['Chittagong Sadar-Chitt. Customs Acca'],
							['Chittagong Sadar-Chitt. Politechnic In'],
							['Chittagong Sadar-Chitt. Sailers Colon'],
							['Chittagong Sadar-Chittagong Airport'],
							['Chittagong Sadar-Chittagong Bandar'],
							['Chittagong Sadar-Chittagong GPO'],
							['Chittagong Sadar-Export Processing'],
							['Chittagong Sadar-Firozshah'],
							['Chittagong Sadar-Halishahar'],
							['Chittagong Sadar-Halishshar'],
							['Chittagong Sadar-Jalalabad'],
							['Chittagong Sadar-Jaldia Merine Accade'],
							['Chittagong Sadar-Middle Patenga'],
							['Chittagong Sadar-Mohard'],
							['Chittagong Sadar-North Halishahar'],
							['Chittagong Sadar-North Katuli'],
							['Chittagong Sadar-Pahartoli'],
							['Chittagong Sadar-Patenga'],
							['Chittagong Sadar-Rampura TSO'],
							['Chittagong Sadar-Wazedia'],
							['East Joara-Barma'],
							['East Joara-Dohazari'],
							['East Joara-East Joara'],
							['East Joara-Gachbaria'],
							['Fatikchhari-Bhandar Sharif'],
							['Fatikchhari-Fatikchhari'],
							['Fatikchhari-Harualchhari'],
							['Fatikchhari-Najirhat'],
							['Fatikchhari-Nanupur'],
							['Fatikchhari-Narayanhat'],
							['Hathazari-Chitt.University'],
							['Hathazari-Fatahabad'],
							['Hathazari-Gorduara'],
							['Hathazari-Hathazari'],
							['Hathazari-Katirhat'],
							['Hathazari-Madrasa'],
							['Hathazari-Mirzapur'],
							['Hathazari-Nuralibari'],
							['Hathazari-Yunus Nagar'],
							['Jaldi-Banigram'],
							['Jaldi-Gunagari'],
							['Jaldi-Jaldi'],
							['Jaldi-Khan Bahadur'],
							['Lohagara-Chunti'],
							['Lohagara-Lohagara'],
							['Lohagara-Padua'],
							['Mirsharai-Abutorab'],
							['Mirsharai-Azampur'],
							['Mirsharai-Bharawazhat'],
							['Mirsharai-Darrogahat'],
							['Mirsharai-Joarganj'],
							['Mirsharai-Korerhat'],
							['Mirsharai-Mirsharai'],
							['Mirsharai-Mohazanhat'],
							['Patia Head Office-Budhpara'],
							['Patia Head Office-Patia Head Office'],
							['Rangunia-Dhamair'],
							['Rangunia-Rangunia'],
							['Rouzan-B.I.T Post Office'],
							['Rouzan-Beenajuri'],
							['Rouzan-Dewanpur'],
							['Rouzan-Fatepur'],
							['Rouzan-Gahira'],
							['Rouzan-Guzra Noapara'],
							['Rouzan-jagannath Hat'],
							['Rouzan-Kundeshwari'],
							['Rouzan-Mohamuni'],
							['Rouzan-Rouzan'],
							['Sandwip-Sandwip'],
							['Sandwip-Shiberhat'],
							['Sandwip-Urirchar'],
							['Satkania-Baitul Ijjat'],
							['Satkania-Bazalia'],
							['Satkania-Satkania'],
							['Sitakunda-Barabkunda'],
							['Sitakunda-Baroidhala'],
							['Sitakunda-Bawashbaria'],
							['Sitakunda-Bhatiari'],
							['Sitakunda-Fouzdarhat'],
							['Sitakunda-Jafrabad'],
							['Sitakunda-Kumira'],
							['Sitakunda-Sitakunda'],
							['Barura-Barura'],
							['Barura-Murdafarganj'],
							['Barura-Poyalgachha'],
							['Brahmanpara-Brahmanpara'],
							['Burichang-Burichang'],
							['Burichang-Maynamoti bazar'],
							['Chandina-Chandia'],
							['Chandina-Madhaiabazar'],
							['Chouddagram-Batisa'],
							['Chouddagram-Chiora'],
							['Chouddagram-Chouddagram'],
							['Comilla Sadar-Comilla Contoment'],
							['Comilla Sadar-Comilla Sadar'],
							['Comilla Sadar-Courtbari'],
							['Comilla Sadar-Halimanagar'],
							['Comilla Sadar-Suaganj'],
							['Daudkandi-Dashpara'],
							['Daudkandi-Daudkandi'],
							['Daudkandi-Eliotganj'],
							['Daudkandi-Gouripur'],
							['Davidhar-Barashalghar'],
							['Davidhar-Davidhar'],
							['Davidhar-Dhamtee'],
							['Davidhar-Gangamandal'],
							['Homna-Homna'],
							['Laksam-Bipulasar'],
							['Laksam-Laksam'],
							['Laksam-Lakshamanpur'],
							['Langalkot-Chhariabazar'],
							['Langalkot-Dhalua'],
							['Langalkot-Gunabati'],
							['Langalkot-Langalkot'],
							['Muradnagar-Bangra'],
							['Muradnagar-Companyganj'],
							['Muradnagar-Muradnagar'],
							['Muradnagar-Pantibazar'],
							['Muradnagar-Ramchandarpur'],
							['Muradnagar-Sonakanda'],
							['Chiringga-Badarkali'],
							['Chiringga-Chiringga'],
							['Chiringga-Chiringga S.O'],
							['Chiringga-Malumghat'],
							['Coxs Bazar Sadar-Coxs Bazar Sadar'],
							['Coxs Bazar Sadar-Eidga'],
							['Coxs Bazar Sadar-Zhilanja'],
							['Gorakghat-Gorakghat'],
							['Kutubdia-Kutubdia'],
							['Ramu-Ramu'],
							['Teknaf-Hnila'],
							['Teknaf-St.Martin'],
							['Teknaf-Teknaf'],
							['Ukhia-Ukhia'],
							['Chhagalnaia-Chhagalnaia'],
							['Chhagalnaia-Daraga Hat'],
							['Chhagalnaia-Maharajganj'],
							['Chhagalnaia-Puabashimulia'],
							['Dagonbhuia-Chhilonia'],
							['Dagonbhuia-Dagondhuia'],
							['Dagonbhuia-Dudmukha'],
							['Dagonbhuia-Rajapur'],
							['Feni Sadar-Fazilpur'],
							['Feni Sadar-Feni Sadar'],
							['Feni Sadar-Laskarhat'],
							['Feni Sadar-Sharshadie'],
							['Pashurampur-Fulgazi'],
							['Pashurampur-Munshirhat'],
							['Pashurampur-Pashurampur'],
							['Pashurampur-Shuarbazar'],
							['Sonagazi-Ahmadpur'],
							['Sonagazi-Kazirhat'],
							['Sonagazi-Motiganj'],
							['Sonagazi-Sonagazi'],
							['Diginala-Diginala'],
							['Khagrachari Sadar-Khagrachari Sadar'],
							['Laxmichhari-Laxmichhari'],
							['Mahalchhari-Mahalchhari'],
							['Manikchhari-Manikchhari'],
							['Matiranga-Matiranga'],
							['Panchhari-Panchhari'],
							['Ramghar Head Office-Ramghar Head Office'],
							['Char Alexgander-Char Alexgander '],
							['Char Alexgander-Hajirghat'],
							['Char Alexgander-Ramgatirhat'],
							['Lakshimpur Sadar-Amani Lakshimpur'],
							['Lakshimpur Sadar-Bhabaniganj'],
							['Lakshimpur Sadar-Chandraganj'],
							['Lakshimpur Sadar-Choupalli'],
							['Lakshimpur Sadar-Dalal Bazar'],
							['Lakshimpur Sadar-Duttapara'],
							['Lakshimpur Sadar-Keramatganj'],
							['Lakshimpur Sadar-Lakshimpur Sadar'],
							['Lakshimpur Sadar-Mandari'],
							['Lakshimpur Sadar-Rupchara'],
							['Ramganj-Alipur'],
							['Ramganj-Dolta'],
							['Ramganj-Kanchanpur'],
							['Ramganj-Naagmud'],
							['Ramganj-Panpara'],
							['Ramganj-Ramganj'],
							['Raypur-Bhuabari'],
							['Raypur-Haydarganj'],
							['Raypur-Nagerdighirpar'],
							['Raypur-Rakhallia'],
							['Raypur-Raypur'],
							['Basurhat-Basur Hat'],
							['Basurhat-Charhajari'],
							['Begumganj-Alaiarpur'],
							['Begumganj-Amisha Para'],
							['Begumganj-Banglabazar'],
							['Begumganj-Bazra'],
							['Begumganj-Begumganj'],
							['Begumganj-Bhabani Jibanpur'],
							['Begumganj-Choumohani'],
							['Begumganj-Dauti'],
							['Begumganj-Durgapur'],
							['Begumganj-Gopalpur'],
							['Begumganj-Jamidar Hat'],
							['Begumganj-Joyag'],
							['Begumganj-Joynarayanpur'],
							['Begumganj-Khalafat Bazar'],
							['Begumganj-Khalishpur'],
							['Begumganj-Maheshganj'],
							['Begumganj-Mir Owarishpur'],
							['Begumganj-Nadona'],
							['Begumganj-Nandiapara'],
							['Begumganj-Oachhekpur'],
							['Begumganj-Rajganj'],
							['Begumganj-Sonaimuri'],
							['Begumganj-Tangirpar'],
							['Begumganj-Thanar Hat'],
							['Chatkhil-Bansa Bazar'],
							['Chatkhil-Bodalcourt'],
							['Chatkhil-Chatkhil'],
							['Chatkhil-Dosh Gharia'],
							['Chatkhil-Karihati'],
							['Chatkhil-Khilpara'],
							['Chatkhil-Palla'],
							['Chatkhil-Rezzakpur'],
							['Chatkhil-Sahapur'],
							['Chatkhil-Sampara'],
							['Chatkhil-Shingbahura'],
							['Chatkhil-Solla'],
							['Hatiya-Afazia'],
							['Hatiya-Hatiya'],
							['Hatiya-Tamoraddi'],
							['Noakhali Sadar-Chaprashir Hat'],
							['Noakhali Sadar-Char Jabbar'],
							['Noakhali Sadar-Charam Tua'],
							['Noakhali Sadar-Din Monir Hat'],
							['Noakhali Sadar-Kabirhat'],
							['Noakhali Sadar-Khalifar Hat'],
							['Noakhali Sadar-Mriddarhat'],
							['Noakhali Sadar-Noakhali College'],
							['Noakhali Sadar-Noakhali Sadar'],
							['Noakhali Sadar-Pak Kishoreganj'],
							['Noakhali Sadar-Sonapur'],
							['Senbag-Beezbag'],
							['Senbag-Chatarpaia'],
							['Senbag-Kallyandi'],
							['Senbag-Kankirhat'],
							['Senbag-Senbag'],
							['Senbag-T.P. Lamua'],
							['Barakal-Barakal'],
							['Bilaichhari-Bilaichhari'],
							['Jarachhari-Jarachhari'],
							['Kalampati-Betbunia'],
							['Kalampati-Kalampati'],
							['kaptai-Chandraghona'],
							['kaptai-Kaptai'],
							['kaptai-Kaptai Nuton Bazar'],
							['kaptai-Kaptai Project'],
							['Longachh-Longachh'],
							['Marishya-Marishya'],
							['Naniachhar-Nanichhar'],
							['Rajsthali-Rajsthali'],
							['Rangamati Sadar-Rangamati Sadar'],
							['Demra-Demra'],
							['Demra-Matuail'],
							['Demra-Sarulia'],
							['Dhaka Cantt.-Dhaka CantonmentTSO'],
							['Dhamrai-Dhamrai'],
							['Dhamrai-Kamalpur'],
							['Dhanmondi-Jigatala TSO'],
							['Gulshan-Banani TSO'],
							['Gulshan-Gulshan Model Town '],
							['Jatrabari-Dhania TSO'],
							['Joypara-Joypara'],
							['Joypara-Narisha'],
							['Joypara-Palamganj'],
							['Keraniganj-Ati'],
							['Keraniganj-Dhaka Jute Mills'],
							['Keraniganj-Kalatia'],
							['Keraniganj-Keraniganj'],
							['Khilgaon-KhilgaonTSO'],
							['Khilkhet-KhilkhetTSO'],
							['Lalbag-Posta TSO'],
							['Mirpur-Mirpur TSO'],
							['Mohammadpur-Mohammadpur Housing '],
							['Mohammadpur-Sangsad BhabanTSO'],
							['Motijheel-BangabhabanTSO'],
							['Motijheel-DilkushaTSO'],
							['Nawabganj-Agla'],
							['Nawabganj-Churain'],
							['Nawabganj-Daudpur'],
							['Nawabganj-Hasnabad'],
							['Nawabganj-Khalpar'],
							['Nawabganj-Nawabganj'],
							['New market-New Market TSO'],
							['Palton-Dhaka GPO'],
							['Ramna-Shantinagr TSO'],
							['Sabujbag-Basabo TSO'],
							['Savar-Amin Bazar'],
							['Savar-Dairy Farm'],
							['Savar-EPZ'],
							['Savar-Jahangirnagar Univer'],
							['Savar-Kashem Cotton Mills'],
							['Savar-Rajphulbaria'],
							['Savar-Savar'],
							['Savar-Savar Canttonment'],
							['Savar-Saver P.A.T.C'],
							['Savar-Shimulia'],
							['Sutrapur-Dhaka Sadar HO'],
							['Sutrapur-Gendaria TSO'],
							['Sutrapur-Wari TSO'],
							['Tejgaon-Tejgaon TSO'],
							['Tejgaon Industrial Area-Dhaka Politechnic '],
							['Uttara-Uttara Model TwonTSO'],
							['Alfadanga-Alfadanga'],
							['Bhanga-Bhanga'],
							['Boalmari-Boalmari'],
							['Boalmari-Rupatpat'],
							['Charbhadrasan-Charbadrashan'],
							['Faridpur Sadar-Ambikapur'],
							['Faridpur Sadar-Baitulaman Politecni'],
							['Faridpur Sadar-Faridpursadar'],
							['Faridpur Sadar-Kanaipur'],
							['Madukhali-Kamarkali'],
							['Madukhali-Madukhali'],
							['Nagarkanda-Nagarkanda'],
							['Nagarkanda-Talma'],
							['Sadarpur-Bishwa jaker Manjil'],
							['Sadarpur-Hat Krishapur'],
							['Sadarpur-Sadarpur'],
							['Shriangan-Shriangan'],
							['Gazipur Sadar-B.O.F'],
							['Gazipur Sadar-B.R.R'],
							['Gazipur Sadar-Chandna'],
							['Gazipur Sadar-Gazipur Sadar'],
							['Gazipur Sadar-National University'],
							['Kaliakaar-Kaliakaar'],
							['Kaliakaar-Safipur'],
							['Kaliganj-Kaliganj'],
							['Kaliganj-Pubail'],
							['Kaliganj-Santanpara'],
							['Kaliganj-Vaoal Jamalpur'],
							['Kapashia-kapashia'],
							['Monnunagar-Ershad Nagar'],
							['Monnunagar-Monnunagar'],
							['Monnunagar-Nishat Nagar'],
							['Sreepur-Barmi'],
							['Sreepur-Bashamur'],
							['Sreepur-Boubi'],
							['Sreepur-Kawraid'],
							['Sreepur-Satkhamair'],
							['Sreepur-Sreepur'],
							['Sripur-Rajendrapur'],
							['Sripur-Rajendrapur Canttome'],
							['Gopalganj Sadar-Barfa'],
							['Gopalganj Sadar-Chandradighalia'],
							['Gopalganj Sadar-Gopalganj Sadar'],
							['Gopalganj Sadar-Ulpur'],
							['Kashiani-Jonapur'],
							['Kashiani-Kashiani'],
							['Kashiani-Ramdia College'],
							['Kashiani-Ratoil'],
							['Kotalipara-Kotalipara'],
							['Maksudpur-Batkiamari'],
							['Maksudpur-Khandarpara'],
							['Maksudpur-Maksudpur'],
							['Tungipara-Patgati'],
							['Tungipara-Tungipara'],
							['Dewangonj-Dewangonj'],
							['Dewangonj-Dewangonj S. Mills'],
							['Islampur-Durmoot'],
							['Islampur-Gilabari'],
							['Islampur-Islampur'],
							['Jamalpur-Jamalpur'],
							['Jamalpur-Nandina'],
							['Jamalpur-Narundi'],
							['Malandah-Jamalpur'],
							['Malandah-Mahmoodpur'],
							['Malandah-Malancha'],
							['Malandah-Malandah'],
							['Mathargonj-Balijhuri'],
							['Mathargonj-Mathargonj'],
							['Shorishabari-Bausee'],
							['Shorishabari-Gunerbari'],
							['Shorishabari-Jagannath Ghat'],
							['Shorishabari-Jamuna Sar Karkhana'],
							['Shorishabari-Pingna'],
							['Shorishabari-Shorishabari'],
							['Bajitpur-Bajitpur'],
							['Bajitpur-Laksmipur'],
							['Bajitpur-Sararchar'],
							['Bhairob-Bhairab'],
							['Hossenpur-Hossenpur'],
							['Itna-Itna'],
							['Karimganj-Karimganj'],
							['Katiadi-Gochhihata'],
							['Katiadi-Katiadi'],
							['Kishoreganj Sadar-Kishoreganj S.Mills'],
							['Kishoreganj Sadar-Kishoreganj Sadar'],
							['Kishoreganj Sadar-Maizhati'],
							['Kishoreganj Sadar-Nilganj'],
							['Kuliarchar-Chhoysuti'],
							['Kuliarchar-Kuliarchar'],
							['Mithamoin-Abdullahpur'],
							['Mithamoin-MIthamoin'],
							['Nikli-Nikli'],
							['Ostagram-Ostagram'],
							['Pakundia-Pakundia'],
							['Tarial-Tarial'],
							['Barhamganj-Bahadurpur'],
							['Barhamganj-Barhamganj'],
							['Barhamganj-Nilaksmibandar'],
							['Barhamganj-Umedpur'],
							['kalkini-Kalkini'],
							['kalkini-Sahabrampur'],
							['Madaripur Sadar-Charmugria'],
							['Madaripur Sadar-Habiganj'],
							['Madaripur Sadar-Kulpaddi'],
							['Madaripur Sadar-Madaripur Sadar'],
							['Madaripur Sadar-Mustafapur'],
							['Rajoir-Khalia'],
							['Rajoir-Rajoir'],
							['Doulatpur-Doulatpur'],
							['Gheor-Gheor'],
							['Lechhraganj-Jhitka'],
							['Lechhraganj-Lechhraganj'],
							['Manikganj Sadar-Barangail'],
							['Manikganj Sadar-Gorpara'],
							['Manikganj Sadar-Mahadebpur'],
							['Manikganj Sadar-Manikganj Bazar'],
							['Manikganj Sadar-Manikganj Sadar'],
							['Saturia-Baliati'],
							['Saturia-Saturia'],
							['Shibloya-Aricha'],
							['Shibloya-Shibaloy'],
							['Shibloya-Tewta'],
							['Shibloya-Uthli'],
							['Singari-Baira'],
							['Singari-joymantop'],
							['Singari-Singair'],
							['Gajaria-Gajaria'],
							['Gajaria-Hossendi'],
							['Gajaria-Rasulpur'],
							['Lohajong-Gouragonj'],
							['Lohajong-Gouragonj'],
							['Lohajong-Haldia SO'],
							['Lohajong-Haridia'],
							['Lohajong-Haridia DESO'],
							['Lohajong-Korhati'],
							['Lohajong-Lohajang'],
							['Lohajong-Madini Mandal'],
							['Lohajong-Medini Mandal EDSO'],
							['Munshiganj Sadar-Kathakhali'],
							['Munshiganj Sadar-Mirkadim'],
							['Munshiganj Sadar-Munshiganj Sadar'],
							['Munshiganj Sadar-Rikabibazar'],
							['Sirajdikhan-Ichapur'],
							['Sirajdikhan-Kola'],
							['Sirajdikhan-Malkha Nagar'],
							['Sirajdikhan-Shekher Nagar'],
							['Sirajdikhan-Sirajdikhan'],
							['Srinagar-Baghra'],
							['Srinagar-Barikhal'],
							['Srinagar-Bhaggyakul'],
							['Srinagar-Hashara'],
							['Srinagar-Kolapara'],
							['Srinagar-Kumarbhog'],
							['Srinagar-Mazpara'],
							['Srinagar-Srinagar'],
							['Srinagar-Vaggyakul SO'],
							['Tangibari-Bajrajugini'],
							['Tangibari-Baligao'],
							['Tangibari-Betkahat'],
							['Tangibari-Dighirpar'],
							['Tangibari-Hasail'],
							['Tangibari-Pura'],
							['Tangibari-Pura EDSO'],
							['Tangibari-Tangibari'],
							['Bhaluka-Bhaluka'],
							['Fulbaria-Fulbaria'],
							['Gaforgaon-Duttarbazar'],
							['Gaforgaon-Gaforgaon'],
							['Gaforgaon-Kandipara'],
							['Gaforgaon-Shibganj'],
							['Gaforgaon-Usti'],
							['Gouripur-Gouripur'],
							['Gouripur-Ramgopalpur'],
							['Haluaghat-Dhara'],
							['Haluaghat-Haluaghat'],
							['Haluaghat-Munshirhat'],
							['Isshwargonj-Atharabari'],
							['Isshwargonj-Isshwargonj'],
							['Isshwargonj-Sohagi'],
							['Muktagachha-Muktagachha'],
							['Mymensingh Sadar-Agriculture Universi'],
							['Mymensingh Sadar-Biddyaganj'],
							['Mymensingh Sadar-Kawatkhali'],
							['Mymensingh Sadar-Mymensingh Sadar'],
							['Mymensingh Sadar-Pearpur'],
							['Mymensingh Sadar-Shombhuganj'],
							['Nandail-Gangail'],
							['Nandail-Nandail'],
							['Phulpur-Beltia'],
							['Phulpur-Phulpur'],
							['Phulpur-Tarakanda'],
							['Trishal-Ahmadbad'],
							['Trishal-Dhala'],
							['Trishal-Ram Amritaganj'],
							['Trishal-Trishal'],
							['Araihazar-Araihazar'],
							['Araihazar-Gopaldi'],
							['Baidder Bazar-Baidder Bazar'],
							['Baidder Bazar-Bara Nagar'],
							['Baidder Bazar-Barodi'],
							['Bandar-Bandar'],
							['Bandar-BIDS'],
							['Bandar-D.C Mills'],
							['Bandar-Madanganj'],
							['Bandar-Nabiganj'],
							['Fatullah-Fatulla Bazar'],
							['Fatullah-Fatullah'],
							['Narayanganj Sadar-Narayanganj Sadar'],
							['Rupganj-Bhulta'],
							['Rupganj-Kanchan'],
							['Rupganj-Murapara'],
							['Rupganj-Nagri'],
							['Rupganj-Rupganj'],
							['Siddirganj-Adamjeenagar'],
							['Siddirganj-LN Mills'],
							['Siddirganj-Siddirganj'],
							['Belabo-Belabo'],
							['Monohordi-Hatirdia'],
							['Monohordi-Katabaria'],
							['Monohordi-Monohordi'],
							['Narshingdi Sadar-Karimpur'],
							['Narshingdi Sadar-Madhabdi'],
							['Narshingdi Sadar-Narshingdi College'],
							['Narshingdi Sadar-Narshingdi Sadar'],
							['Narshingdi Sadar-Panchdona'],
							['Narshingdi Sadar-UMC Jute Mills'],
							['Palash-Char Sindhur'],
							['Palash-Ghorashal'],
							['Palash-Ghorashal Urea Facto'],
							['Palash-Palash'],
							['Raypura-Bazar Hasnabad'],
							['Raypura-Radhaganj bazar'],
							['Raypura-Raypura'],
							['Shibpur-Shibpur'],
							[' Susung Durgapur-Susnng Durgapur'],
							['Atpara-Atpara'],
							['Barhatta-Barhatta'],
							['Dharmapasha-Dharampasha'],
							['Dhobaura-Dhobaura'],
							['Dhobaura-Sakoai'],
							['Kalmakanda-Kalmakanda'],
							['Kendua-Kendua'],
							['Khaliajuri-Khaliajhri'],
							['Khaliajuri-Shaldigha'],
							['Madan-Madan'],
							['Moddhynagar-Moddoynagar'],
							['Mohanganj-Mohanganj'],
							['Netrakona Sadar-Baikherhati'],
							['Netrakona Sadar-Netrakona Sadar'],
							['Purbadhola-Jaria Jhanjhail'],
							['Purbadhola-Purbadhola'],
							['Purbadhola-Shamgonj'],
							['Baliakandi-Baliakandi'],
							['Baliakandi-Nalia'],
							['Pangsha-Mrigibazar'],
							['Pangsha-Pangsha'],
							['Pangsha-Ramkol'],
							['Pangsha-Ratandia'],
							['Rajbari Sadar-Goalanda'],
							['Rajbari Sadar-Khankhanapur'],
							['Rajbari Sadar-Rajbari Sadar'],
							['Bhedorganj-Bhedorganj'],
							['Damudhya-Damudhya'],
							['Gosairhat-Gosairhat'],
							['Jajira-Jajira'],
							['Naria-Bhozeshwar'],
							['Naria-Gharisar'],
							['Naria-Kartikpur'],
							['Naria-Naria'],
							['Naria-Upshi'],
							['Shariatpur Sadar-Angaria'],
							['Shariatpur Sadar-Chikandi'],
							['Shariatpur Sadar-Shariatpur Sadar'],
							['Bakshigonj-Bakshigonj'],
							['Jhinaigati-Jhinaigati'],
							['Nakla-Gonopaddi'],
							['Nakla-Nakla'],
							['Nalitabari-Hatibandha'],
							['Nalitabari-Nalitabari'],
							['Sherpur Shadar-Sherpur Shadar'],
							['Shribardi-Shribardi'],
							['Basail-Basail'],
							['Bhuapur-Bhuapur'],
							['Delduar-Delduar'],
							['Delduar-Elasin'],
							['Delduar-Hinga Nagar'],
							['Delduar-Jangalia'],
							['Delduar-Lowhati'],
							['Delduar-Patharail'],
							['Ghatail-D. Pakutia'],
							['Ghatail-Dhalapara'],
							['Ghatail-Ghatial'],
							['Ghatail-Lohani'],
							['Ghatail-Zahidganj'],
							['Gopalpur-Gopalpur'],
							['Gopalpur-Hemnagar'],
							['Gopalpur-Jhowail'],
							['Kalihati-Ballabazar'],
							['Kalihati-Elinga'],
							['Kalihati-Kalihati'],
							['Kalihati-Nagarbari'],
							['Kalihati-Nagarbari SO'],
							['Kalihati-Nagbari'],
							['Kalihati-Palisha'],
							['Kalihati-Rajafair'],
							['Kashkaolia-Kashkawlia'],
							['Madhupur-Dhobari'],
							['Madhupur-Madhupur'],
							['Mirzapur-Gorai'],
							['Mirzapur-Jarmuki'],
							['Mirzapur-M.C. College'],
							['Mirzapur-Mirzapur'],
							['Mirzapur-Mohera'],
							['Mirzapur-Warri paikpara'],
							['Nagarpur-Dhuburia'],
							['Nagarpur-Nagarpur'],
							['Nagarpur-Salimabad'],
							['Sakhipur-Kochua'],
							['Sakhipur-Sakhipur'],
							['Tangail Sadar-Kagmari'],
							['Tangail Sadar-Korotia'],
							['Tangail Sadar-Purabari'],
							['Tangail Sadar-Santosh'],
							['Tangail Sadar-Tangail Sadar'],
							['Alamdanga-Alamdanga'],
							['Alamdanga-Hardi'],
							['Chuadanga Sadar-Chuadanga Sadar'],
							['Chuadanga Sadar-Munshiganj'],
							['Damurhuda-Andulbaria'],
							['Damurhuda-Damurhuda'],
							['Damurhuda-Darshana'],
							['Doulatganj-Doulatganj'],
							['Bagerhat Sadar-Bagerhat Sadar'],
							['Bagerhat Sadar-P.C College'],
							['Bagerhat Sadar-Rangdia'],
							['Chalna Ankorage-Chalna Ankorage'],
							['Chalna Ankorage-Mongla Port'],
							['Chitalmari-Barabaria'],
							['Chitalmari-Chitalmari'],
							['Fakirhat-Bhanganpar Bazar'],
							['Fakirhat-Fakirhat'],
							['Fakirhat-Mansa'],
							['Kachua UPO-Kachua'],
							['Kachua UPO-Sonarkola'],
							['Mollahat-Charkulia'],
							['Mollahat-Dariala'],
							['Mollahat-Kahalpur'],
							['Mollahat-Mollahat'],
							['Mollahat-Nagarkandi'],
							['Mollahat-Pak Gangni'],
							['Morelganj-Morelganj'],
							['Morelganj-Sannasi Bazar'],
							['Morelganj-Telisatee'],
							['Rampal-Foylahat'],
							['Rampal-Gourambha'],
							['Rampal-Rampal'],
							['Rampal-Sonatunia'],
							['Rayenda-Rayenda'],
							['Bagharpara-Bagharpara'],
							['Bagharpara-Gouranagar'],
							['Chaugachha-Chougachha'],
							['Jessore Sadar-Basundia'],
							['Jessore Sadar-Chanchra'],
							['Jessore Sadar-Churamankathi'],
							['Jessore Sadar-Jessore Airbach'],
							['Jessore Sadar-Jessore canttonment'],
							['Jessore Sadar-Jessore Sadar'],
							['Jessore Sadar-Jessore Upa-Shahar'],
							['Jessore Sadar-Rupdia'],
							['Jhikargachha-Jhikargachha'],
							['Keshabpur-Keshobpur'],
							['Monirampur-Monirampur'],
							['Noapara-Bhugilhat'],
							['Noapara-Noapara'],
							['Noapara-Rajghat'],
							['Sarsa-Bag Achra'],
							['Sarsa-Benapole'],
							['Sarsa-Jadabpur'],
							['Sarsa-Sarsa'],
							['Harinakundu-Harinakundu'],
							['Jinaidaha Sadar-Jinaidaha Cadet College'],
							['Jinaidaha Sadar-Jinaidaha Sadar'],
							['Kotchandpur-Kotchandpur'],
							['Maheshpur-Maheshpur'],
							['Naldanga-Hatbar Bazar'],
							['Naldanga-Naldanga'],
							['Shailakupa-Kumiradaha'],
							['Shailakupa-Shailakupa'],
							['Alaipur-Alaipur'],
							['Alaipur-Belphulia'],
							['Alaipur-Rupsha'],
							['Batiaghat-Batiaghat'],
							['Batiaghat-Surkalee'],
							['Chalna Bazar-Bajua'],
							['Chalna Bazar-Chalna Bazar'],
							['Chalna Bazar-Dakup'],
							['Chalna Bazar-Nalian'],
							['Digalia-Chandni Mahal'],
							['Digalia-Digalia'],
							['Digalia-Gazirhat'],
							['Digalia-Ghoshghati'],
							['Digalia-Senhati'],
							['Khulna Sadar-Atra Shilpa Area'],
							['Khulna Sadar-BIT Khulna'],
							['Khulna Sadar-Doulatpur'],
							['Khulna Sadar-Jahanabad Canttonmen'],
							['Khulna Sadar-Khula Sadar'],
							['Khulna Sadar-Khulna G.P.O'],
							['Khulna Sadar-Khulna Shipyard'],
							['Khulna Sadar-Khulna University'],
							['Khulna Sadar-Siramani'],
							['Khulna Sadar-Sonali Jute Mills'],
							['Madinabad-Amadee'],
							['Madinabad-Madinabad'],
							['Paikgachha-Chandkhali'],
							['Paikgachha-Garaikhali'],
							['Paikgachha-Godaipur'],
							['Paikgachha-Kapilmoni'],
							['Paikgachha-Katipara'],
							['Paikgachha-Paikgachha'],
							['Phultala-Phultala'],
							['Sajiara-Chuknagar'],
							['Sajiara-Ghonabanda'],
							['Sajiara-Sajiara'],
							['Sajiara-Shahapur'],
							['Terakhada-Pak Barasat'],
							['Terakhada-Terakhada'],
							['Bheramara-Allardarga'],
							['Bheramara-Bheramara'],
							['Bheramara-Ganges Bheramara'],
							['Janipur-Janipur'],
							['Janipur-Khoksa'],
							['Kumarkhali-Kumarkhali'],
							['Kumarkhali-Panti'],
							['Kustia Sadar-Islami University'],
							['Kustia Sadar-Jagati'],
							['Kustia Sadar-Kushtia Mohini'],
							['Kustia Sadar-Kustia Sadar'],
							['Mirpur-Amla Sadarpur'],
							['Mirpur-Mirpur'],
							['Mirpur-Poradaha'],
							['Rafayetpur-Khasmathurapur'],
							['Rafayetpur-Rafayetpur'],
							['Rafayetpur-Taragunia'],
							['Arpara-Arpara'],
							['Magura Sadar-Magura Sadar'],
							['Mohammadpur-Binodpur'],
							['Mohammadpur-Mohammadpur'],
							['Mohammadpur-Nahata'],
							['Shripur-Langalbadh'],
							['Shripur-Nachol'],
							['Shripur-Shripur'],
							['Gangni-Gangni'],
							['Meherpur Sadar-Amjhupi'],
							['Meherpur Sadar-Amjhupi'],
							['Meherpur Sadar-Meherpur Sadar'],
							['Meherpur Sadar-Mujib Nagar Complex'],
							['Kalia-Kalia'],
							['Laxmipasha-Baradia'],
							['Laxmipasha-Itna'],
							['Laxmipasha-Laxmipasha'],
							['Laxmipasha-Lohagora'],
							['Laxmipasha-Naldi'],
							['Mohajan-Mohajan'],
							['Narail Sadar-Narail Sadar'],
							['Narail Sadar-Ratanganj'],
							['Ashashuni-Ashashuni'],
							['Ashashuni-Baradal'],
							['Debbhata-Debbhata'],
							['Debbhata-Gurugram'],
							['kalaroa-Chandanpur'],
							['kalaroa-Hamidpur'],
							['kalaroa-Jhaudanga'],
							['kalaroa-kalaroa'],
							['kalaroa-Khordo'],
							['kalaroa-Murarikati'],
							['Kaliganj UPO-Kaliganj UPO'],
							['Kaliganj UPO-Nalta Mubaroknagar'],
							['Kaliganj UPO-Ratanpur '],
							['Nakipur-Buri Goalini'],
							['Nakipur-Gabura'],
							['Nakipur-Habinagar'],
							['Nakipur-Nakipur'],
							['Nakipur-Naobeki'],
							['Nakipur-Noornagar'],
							['Satkhira Sadar-Budhhat'],
							['Satkhira Sadar-Gunakar kati'],
							['Satkhira Sadar-Satkhira Islamia Acc'],
							['Satkhira Sadar-Satkhira Sadar'],
							['Taala-Patkelghata'],
							['Taala-Taala'],
							['Alamdighi-Adamdighi'],
							['Alamdighi-Nasharatpur'],
							['Alamdighi-Santahar'],
							['Bogra Sadar-Bogra Canttonment'],
							['Bogra Sadar-Bogra Sadar'],
							['Dhunat-Dhunat'],
							['Dhunat-Gosaibari'],
							['Dupchachia-Dupchachia'],
							['Dupchachia-Talora'],
							['Gabtoli-Gabtoli'],
							['Gabtoli-Sukhanpukur'],
							['Kahalu-Kahalu'],
							['Nandigram-Nandigram'],
							['Sariakandi-Chandan Baisha'],
							['Sariakandi-Sariakandi'],
							['Sherpur-Chandaikona'],
							['Sherpur-Palli Unnyan Accadem'],
							['Sherpur-Sherpur'],
							['Shibganj-Shibganj'],
							['Sonatola-Sonatola'],
							['Bholahat-Bholahat'],
							['Chapinawabganj Sadar-Amnura'],
							['Chapinawabganj Sadar-Chapinawbganj Sadar'],
							['Chapinawabganj Sadar-Rajarampur'],
							['Chapinawabganj Sadar-Ramchandrapur'],
							['Nachol-Mandumala'],
							['Nachol-Nachol'],
							['Rohanpur-Gomashtapur'],
							['Rohanpur-Rohanpur'],
							['Shibganj U.P.O-Kansart'],
							['Shibganj U.P.O-Manaksha'],
							['Shibganj U.P.O-Shibganj U.P.O'],
							['Akkelpur-Akklepur'],
							['Akkelpur-jamalganj'],
							['Akkelpur-Tilakpur'],
							['Joypurhat Sadar-Joypurhat Sadar'],
							['kalai-kalai'],
							['Khetlal-Khetlal'],
							['panchbibi-Panchbibi'],
							['Ahsanganj-Ahsanganj'],
							['Ahsanganj-Bandai'],
							['Badalgachhi-Badalgachhi'],
							['Dhamuirhat-Dhamuirhat'],
							['Mahadebpur-Mahadebpur'],
							['Naogaon Sadar-Naogaon Sadar'],
							['Niamatpur-Niamatpur'],
							['Nitpur-Nitpur'],
							['Nitpur-Panguria'],
							['Nitpur-Porsa'],
							['Patnitala-Patnitala'],
							['Prasadpur-Balihar'],
							['Prasadpur-Manda'],
							['Prasadpur-Prasadpur'],
							['Raninagar-Kashimpur'],
							['Raninagar-Raninagar'],
							['Sapahar-Moduhil'],
							['Sapahar-Sapahar'],
							['Gopalpur UPO-Abdulpur'],
							['Gopalpur UPO-Gopalpur U.P.O'],
							['Gopalpur UPO-Lalpur S.O'],
							['Harua-Baraigram'],
							['Harua-Dayarampur'],
							['Harua-Harua'],
							['Hatgurudaspur-Hatgurudaspur'],
							['Laxman-Laxman'],
							['Natore Sadar-Baiddyabal Gharia'],
							['Natore Sadar-Digapatia'],
							['Natore Sadar-Madhnagar'],
							['Natore Sadar-Natore Sadar'],
							['Singra-Singra'],
							['Banwarinagar-Banwarinagar'],
							['Bera-Bera'],
							['Bera-Kashinathpur'],
							['Bera-Nakalia'],
							['Bera-Puran Bharenga'],
							['Bhangura-Bhangura'],
							['Chatmohar-Chatmohar'],
							['Debottar-Debottar'],
							['Ishwardi-Dhapari'],
							['Ishwardi-Ishwardi'],
							['Ishwardi-Pakshi'],
							['Ishwardi-Rajapur'],
							['Pabna Sadar-Hamayetpur'],
							['Pabna Sadar-Kaliko Cotton Mills'],
							['Pabna Sadar-Pabna Sadar'],
							['Sathia-Sathia'],
							['Sujanagar-Sagarkandi'],
							['Sujanagar-Sujanagar'],
							['Bagha-Arani'],
							['Bagha-Bagha'],
							['Bhabaniganj-Bhabaniganj'],
							['Bhabaniganj-Taharpur'],
							['Charghat-Charghat'],
							['Charghat-Sarda'],
							['Durgapur-Durgapur'],
							['Godagari-Godagari'],
							['Godagari-Premtoli'],
							['Khod Mohanpur-Khodmohanpur'],
							['Lalitganj-Lalitganj'],
							['Lalitganj-Rajshahi Sugar Mills'],
							['Lalitganj-Shyampur'],
							['Putia-Putia'],
							['Rajshahi Sadar-Binodpur Bazar'],
							['Rajshahi Sadar-Ghuramara'],
							['Rajshahi Sadar-Kazla'],
							['Rajshahi Sadar-Rajshahi Canttonment'],
							['Rajshahi Sadar-Rajshahi Court'],
							['Rajshahi Sadar-Rajshahi Sadar'],
							['Rajshahi Sadar-Rajshahi University'],
							['Rajshahi Sadar-Sapura'],
							['Tanor-Tanor'],
							['Baiddya Jam Toil-Baiddya Jam Toil'],
							['Belkuchi-Belkuchi'],
							['Belkuchi-Enayetpur'],
							['Belkuchi-Rajapur'],
							['Belkuchi-Sohagpur'],
							['Belkuchi-Sthal'],
							['Dhangora-Dhangora'],
							['Dhangora-Malonga'],
							['Kazipur-Gandail'],
							['Kazipur-Kazipur'],
							['Kazipur-Shuvgachha'],
							['Shahjadpur-Jamirta'],
							['Shahjadpur-Kaijuri'],
							['Shahjadpur-Porjana'],
							['Shahjadpur-Shahjadpur'],
							['Sirajganj Sadar-Raipur'],
							['Sirajganj Sadar-Rashidabad'],
							['Sirajganj Sadar-Sirajganj Sadar'],
							['Tarash-Tarash'],
							['Ullapara-Lahiri Mohanpur'],
							['Ullapara-Salap'],
							['Ullapara-Ullapara'],
							['Ullapara-Ullapara R.S'],
							['Azmireeganj-Azmireeganj'],
							['Bahubal-Bahubal'],
							['Baniachang-Baniachang'],
							['Baniachang-Jatrapasha'],
							['Baniachang-Kadirganj'],
							['Chunarughat-Chandpurbagan'],
							['Chunarughat-Chunarughat'],
							['Chunarughat-Narapati'],
							['Hobiganj Sadar-Gopaya'],
							['Hobiganj Sadar-Hobiganj Sadar'],
							['Hobiganj Sadar-Shaestaganj'],
							['Kalauk-Kalauk'],
							['Kalauk-Lakhai'],
							['Madhabpur-Itakhola'],
							['Madhabpur-Madhabpur'],
							['Madhabpur-Saihamnagar'],
							['Madhabpur-Shahajibazar'],
							['Nabiganj-Digalbak'],
							['Nabiganj-Golduba'],
							['Nabiganj-Goplarbazar'],
							['Nabiganj-Inathganj'],
							['Nabiganj-Nabiganj'],
							['Baralekha-Baralekha'],
							['Baralekha-Dhakkhinbag'],
							['Baralekha-Juri'],
							['Baralekha-Purbashahabajpur'],
							['Kamalganj-Kamalganj'],
							['Kamalganj-Keramatnaga'],
							['Kamalganj-Munshibazar'],
							['Kamalganj-Patrakhola'],
							['Kamalganj-Shamsher Nagar'],
							['Kulaura-Baramchal'],
							['Kulaura-Kajaldhara'],
							['Kulaura-Karimpur'],
							['Kulaura-Kulaura'],
							['Kulaura-Langla'],
							['Kulaura-Prithimpasha'],
							['Kulaura-Tillagaon'],
							['Moulvibazar Sadar-Afrozganj'],
							['Moulvibazar Sadar-Barakapan'],
							['Moulvibazar Sadar-Monumukh'],
							['Moulvibazar Sadar-Moulvibazar Sadar'],
							['Rajnagar-Rajnagar'],
							['Srimangal-Kalighat'],
							['Srimangal-Khejurichhara'],
							['Srimangal-Narain Chora'],
							['Srimangal-Satgaon'],
							['Srimangal-Srimangal'],
							['Bishamsarpur-Bishamsapur'],
							['Chhatak-Chhatak'],
							['Chhatak-Chhatak Cement Facto'],
							['Chhatak-Chhatak Paper Mills'],
							['Chhatak-Chourangi Bazar'],
							['Chhatak-Gabindaganj'],
							['Chhatak-Gabindaganj Natun Ba'],
							['Chhatak-Islamabad'],
							['Chhatak-jahidpur'],
							['Chhatak-Khurma'],
							['Chhatak-Moinpur'],
							['Dhirai Chandpur-Dhirai Chandpur'],
							['Dhirai Chandpur-Jagdal'],
							['Duara bazar-Duara bazar'],
							['Ghungiar-Ghungiar'],
							['Jagnnathpur-Atuajan'],
							['Jagnnathpur-Hasan Fatemapur'],
							['Jagnnathpur-Jagnnathpur'],
							['Jagnnathpur-Rasulganj'],
							['Jagnnathpur-Shiramsi'],
							['Jagnnathpur-Syedpur'],
							['Sachna-Sachna'],
							['Sunamganj Sadar-Pagla'],
							['Sunamganj Sadar-Patharia'],
							['Sunamganj Sadar-Sunamganj Sadar'],
							['Tahirpur-Tahirpur'],
							['Balaganj-Balaganj'],
							['Balaganj-Begumpur'],
							['Balaganj-Brahman Shashon'],
							['Balaganj-Gaharpur'],
							['Balaganj-Goala Bazar'],
							['Balaganj-Karua'],
							['Balaganj-Kathal Khair'],
							['Balaganj-Natun Bazar'],
							['Balaganj-Omarpur'],
							['Balaganj-Tajpur'],
							['Bianibazar-Bianibazar'],
							['Bianibazar-Churkai '],
							['Bianibazar-jaldup'],
							['Bianibazar-Kurar bazar'],
							['Bianibazar-Mathiura'],
							['Bianibazar-Salia bazar'],
							['Bishwanath-Bishwanath'],
							['Bishwanath-Dashghar'],
							['Bishwanath-Deokalas'],
							['Bishwanath-Doulathpur'],
							['Bishwanath-Singer kanch'],
							['Fenchuganj-Fenchuganj'],
							['Fenchuganj-Fenchuganj SareKarkh'],
							['Goainhat-Chiknagul'],
							['Goainhat-Goainhat'],
							['Goainhat-Jaflong'],
							['Gopalganj-banigram'],
							['Gopalganj-Chandanpur'],
							['Gopalganj-Dakkhin Bhadashore'],
							['Gopalganj-Dhaka Dakkhin'],
							['Gopalganj-Gopalgannj'],
							['Gopalganj-Ranaping'],
							['Jaintapur-Jainthapur'],
							['Jakiganj-Ichhamati'],
							['Jakiganj-Jakiganj'],
							['Kanaighat-Chatulbazar'],
							['Kanaighat-Gachbari'],
							['Kanaighat-Kanaighat'],
							['Kanaighat-Manikganj'],
							['Kompanyganj-Kompanyganj'],
							['Sylhet Sadar-Birahimpur'],
							['Sylhet Sadar-Jalalabad'],
							['Sylhet Sadar-Jalalabad Cantoment'],
							['Sylhet Sadar-Kadamtali'],
							['Sylhet Sadar-Kamalbazer'],
							['Sylhet Sadar-Khadimnagar'],
							['Sylhet Sadar-Lalbazar'],
							['Sylhet Sadar-Mogla'],
							['Sylhet Sadar-Ranga Hajiganj'],
							['Sylhet Sadar-Shahajalal Science &'],
							['Sylhet Sadar-Silam'],
							['Sylhet Sadar-Sylhe Sadar'],
							['Sylhet Sadar-Sylhet Biman Bondar'],
							['Sylhet Sadar-Sylhet Cadet Col'],
							['Bangla Hili-Bangla Hili'],
							['Biral-Biral'],
							['Birampur-Birampur'],
							['Birganj-Birganj'],
							['Chrirbandar-Chrirbandar'],
							['Chrirbandar-Ranirbandar'],
							['Dinajpur Sadar-Dinajpur Rajbari'],
							['Dinajpur Sadar-Dinajpur Sadar'],
							['Khansama-Khansama'],
							['Khansama-Pakarhat'],
							['Maharajganj-Maharajganj'],
							['Nababganj-Daudpur'],
							['Nababganj-Gopalpur'],
							['Nababganj-Nababganj'],
							['Osmanpur-Ghoraghat'],
							['Osmanpur-Osmanpur'],
							['Parbatipur-Parbatipur'],
							['Phulbari-Phulbari'],
							['Setabganj-Setabganj'],
							['Bonarpara-Bonarpara'],
							['Bonarpara-saghata'],
							['Gaibandha Sadar-Gaibandha Sadar'],
							['Gobindaganj-Gobindhaganj'],
							['Gobindaganj-Mahimaganj'],
							['Palashbari-Palashbari'],
							['Phulchhari-Bharatkhali'],
							['Phulchhari-Phulchhari'],
							['Saadullapur-Naldanga'],
							['Saadullapur-Saadullapur'],
							['Sundarganj-Bamandanga'],
							['Sundarganj-Sundarganj'],
							['Bhurungamari-Bhurungamari'],
							['Chilmari-Chilmari'],
							['Chilmari-Jorgachh'],
							['Kurigram Sadar-Kurigram Sadar'],
							['Kurigram Sadar-Pandul'],
							['Kurigram Sadar-Phulbari'],
							['Nageshwar-Nageshwar'],
							['Rajarhat-Nazimkhan'],
							['Rajarhat-Rajarhat'],
							['Rajibpur-Rajibpur'],
							['Roumari-Roumari'],
							['Ulipur-Bazarhat'],
							['Ulipur-Ulipur'],
							['Aditmari-Aditmari'],
							['Hatibandha-Hatibandha'],
							['Lalmonirhat Sadar-Kulaghat SO'],
							['Lalmonirhat Sadar-Lalmonirhat Sadar'],
							['Lalmonirhat Sadar-Moghalhat'],
							['Patgram-Baura'],
							['Patgram-Burimari'],
							['Patgram-Patgram'],
							['Tushbhandar-Tushbhandar'],
							['Dimla-Dimla'],
							['Dimla-Ghaga Kharibari'],
							['Domar-Chilahati'],
							['Domar-Domar'],
							['Jaldhaka-Jaldhaka'],
							['Kishoriganj-Kishoriganj'],
							['Nilphamari Sadar-Nilphamari Sadar'],
							['Nilphamari Sadar-Nilphamari Sugar Mil'],
							['Syedpur-Syedpur'],
							['Syedpur-Syedpur Upashahar'],
							['Boda-Boda'],
							['Chotto Dab-Chotto Dab'],
							['Chotto Dab-Mirjapur'],
							['Dabiganj-Dabiganj'],
							['Panchagra Sadar-Panchagar Sadar'],
							['Tetulia-Tetulia'],
							['Badarganj-Badarganj'],
							['Badarganj-Shyampur'],
							['Gangachara-Gangachara'],
							['Kaunia-Haragachh'],
							['Kaunia-Kaunia'],
							['Mithapukur-Mithapukur'],
							['Pirgachha-Pirgachha'],
							['Rangpur Sadar-Alamnagar'],
							['Rangpur Sadar-Mahiganj'],
							['Rangpur Sadar-Rangpur Cadet Colleg'],
							['Rangpur Sadar-Rangpur Carmiecal Col'],
							['Rangpur Sadar-Rangpur Sadar'],
							['Rangpur Sadar-Rangpur Upa-Shahar'],
							['Taraganj-Taraganj'],
							['Baliadangi-Baliadangi'],
							['Baliadangi-Lahiri'],
							['Jibanpur-Jibanpur'],
							['Pirganj-Pirganj'],
							['Pirganj-Pirganj'],
							['Rani Sankail-Nekmarad'],
							['Rani Sankail-Rani Sankail'],
							['Thakurgaon Sadar-Ruhia'],
							['Thakurgaon Sadar-Shibganj'],
							['Thakurgaon Sadar-Thakurgaon Road'],
							['Thakurgaon Sadar-Thakurgaon Sadar']
];


protected $books = [

			['Holud Himu Kalo Rab','Humayun Ahmed'],
			['Kichu Shaisob',],
			['Megher Chaya',],
			['Chader Aloy Koyekjon Jubok',],
			['Ami E Misir Ali',],
			['Krisnopokkho',],
			['Brihonnola',],
			['Aj Himur Biye',],
			['Aynaghor',],
			['Tetul Bone Jochona',],
			['Se Ashe Dhire',],
			['Daruchini Dip',],
			['Amar Ache Jol',],
			['Ekjon Himu o Koyekti Jhin Jhin Poka',],
			['Andhakarer Gan',],
			['Achinpur',],
			['Sabai Geche Bone',],
			['Ural Pankhi',],
			['Voy',],
			['Debi',],
			['Moyurakkhi',],
			['Dui Duari',],
			['Neel Aparajita',],
			['Ebong Himu'],
			['Pakhi Amar Ekla Pakhi',],
			['Rupali Dip',],
			['Rodon Vora E Bosonto',],
			['Brishti Bilash',],
			['Darjar Opashe',],
			['Pufi by Humayun'],
			['Nabani',],
			['Himur Rupali Ratri',],
			['Angul Kata Jaglu',],

];


	public function run()
	{
	//	Eloquent::unguard();
		//$this->user();
		$this->zilla();
		$this->place();
		$this->user();

	}

	public function user()
	{
		$faker = Faker\Factory::create();

		//echo $random_generator = $casus->getGenerator();

			for ($i=0; $i < 1000; $i++) {
				# code...
				$zilla =  rand(1,64);
				$place = rand(1,1349);

				DB::table('users_table')->insert([
				            'username' 		=> $faker->username,
				            'first_name' 	=> $faker->firstName,
				            'last_name' 	=> $faker->lastName,
										'phn_number' 	=> $faker->tollFreePhoneNumber,
										'email'			 	=> $faker->email,
										'password'		=> bcrypt('123456'),
										'library_name'=> $faker->company.' ' . $faker->companySuffix,
										'zilla'				=> $zilla,
										'place'				=> $place,
										'address'			=> $faker->address;
										//'district'		=>
				]);

			}

	}

	public function books()
	{



	}


	public function zilla()
	{

			foreach ($this->districs as $value) {
				# code...
				DB::table('zilla')->insert([
				      	'zilla_name' => $value[0],
								'zilla_bn'	 => $value[1]
				]);

			}

	}

	public function place()
	{
		$random = rand(1,64);

		foreach ($this->places as $value) {
			# code...

			DB::table('place')->insert([
							'zilla_id'	 => $random,
							'place_name' => $value
			]);

		}

	}

}
