<?php

class DatabaseSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */


	 protected $districs = [
	             ['Dhaka','ঢাকা'],
	             ['Faridpur','ফরিদপুর'],
	             ['Gazipur','গাজীপুর'],
	             ['Gopalganj','গোপালগঞ্জ'],
	             ['Jamalpur','জামালপুর'],
	             ['Kishoreganj','কিশোরগঞ্জ'],
	             ['Madaripur','মাদারীপুর'],
	             ['Manikganj','মানিকগঞ্জ'],
	             ['Munshiganj','মুন্সিগঞ্জ'],
	             ['Mymensingh','ময়মনসিং'],
	             ['Narayanganj','নারায়াণগঞ্জ'],
	             ['Narsingdi','নরসিংদী'],
	             ['Netrokona','নেত্রকোনা'],
	             ['Rajbari','রাজবাড়ি'],
	             ['Shariatpur','শরীয়তপুর'],
	             ['Sherpur','শেরপুর'],
	             ['Tangail','টাঙ্গাইল'],
	             ['Bogra','বগুড়া'],
	             ['Joypurhat','জয়পুরহাট'],
	             ['Naogaon','নওগাঁ'],
	             ['Natore','নাটোর'],
	             ['Nawabganj','নবাবগঞ্জ'],
	             ['Pabna','পাবনা'],
	             ['Rajshahi','রাজশাহী'],
	             ['Sirajgonj','সিরাজগঞ্জ'],
	             ['Dinajpur','দিনাজপুর'],
	             ['Gaibandha','গাইবান্ধা'],
	             ['Kurigram','কুড়িগ্রাম'],
	             ['Lalmonirhat','লালমনিরহাট'],
	             ['Nilphamari','নীলফামারী'],
	             ['Panchagarh','পঞ্চগড়'],
	             ['Rangpur','রংপুর'],
	             ['Thakurgaon','ঠাকুরগাঁও'],
	             ['Barguna','বরগুনা'],
	             ['Barisal','বরিশাল'],
	             ['Bhola','ভোলা'],
	             ['Jhalokati','ঝালকাঠি'],
	             ['Patuakhali','পটুয়াখালী'],
	             ['Pirojpur','পিরোজপুর'],
	             ['Bandarban','বান্দরবান'],
	             ['Brahmanbaria','ব্রাহ্মণবাড়িয়া'],
	             ['Chandpur','চাঁদপুর'],
	             ['Chittagong','চট্টগ্রাম'],
	             ['Comilla','কুমিল্লা'],
	             ['Cox\'s Bazar','কক্স বাজার'],
	             ['Feni','ফেনী'],
	             ['Khagrachari','খাগড়াছড়ি'],
	             ['Lakshmipur','লক্ষ্মীপুর'],
	             ['Noakhali','নোয়াখালী'],
	             ['Rangamati','রাঙ্গামাটি'],
	             ['Habiganj','হবিগঞ্জ'],
	             ['Maulvibazar','মৌলভীবাজার'],
	             ['Sunamganj','সুনামগঞ্জ'],
	             ['Sylhet','সিলেট'],
	             ['Bagerhat','বাগেরহাট'],
	             ['Chuadanga','চুয়াডাঙ্গা'],
	             ['Jessore','যশোর'],
	             ['Jhenaidah','ঝিনাইদহ'],
	             ['Khulna','খুলনা'],
	             ['Kushtia','কুষ্টিয়া'],
	             ['Magura','মাগুরা'],
	             ['Meherpur','মেহেরপুর'],
	             ['Narail','নড়াইল'],
	             ['Satkhira','সাতক্ষীরা'],
	         ];

			protected $places = [

							['Amtali-Amtali'],
							['Bamna-Bamna'],
							['Barguna Sadar-Barguna Sadar'],
							['Nali Bandar-Barguna Sadar'],
							['Betagi-Betagi'],
							['Darul Ulam-Betagi'],
							['Kakchira-Patharghata'],
							['Patharghata-Patharghata'],
							['Agailzhara-Agailzhara'],
							['Gaila-Agailzhara'],
							['Paisarhat-Agailzhara'],
							['Babuganj-Babuganj'],
							['Barishal Cadet-Babuganj'],
							['Chandpasha-Babuganj'],
							['Madhabpasha-Babuganj'],
							['Nizamuddin College-Babuganj'],
							['Rahamatpur-Babuganj'],
							['Thakur Mallik-Babuganj'],
							['Barajalia-Barajalia'],
							['Osman Manjil-Barajalia'],
							['Barishal Sadar-Barishal Sadar'],
							['Bukhainagar-Barishal Sadar'],
							['Jaguarhat-Barishal Sadar'],
							['Kashipur-Barishal Sadar'],
							['Patang-Barishal Sadar'],
							['Saheberhat-Barishal Sadar'],
							['Sugandia-Barishal Sadar'],
							['Batajor-Gouranadi'],
							['Gouranadi-Gouranadi'],
							['Kashemabad-Gouranadi'],
							['Tarki Bandar-Gouranadi'],
							['Langutia-Mahendiganj'],
							['Laskarpur-Mahendiganj'],
							['Mahendiganj-Mahendiganj'],
							['Nalgora-Mahendiganj'],
							['Ulania-Mahendiganj'],
							['Charkalekhan-Muladi'],
							['Kazirchar-Muladi'],
							['Muladi-Muladi'],
							['Charamandi-Sahebganj'],
							['kalaskati-Sahebganj'],
							['Padri Shibpur-Sahebganj'],
							['Sahebganj-Sahebganj'],
							['Shialguni-Sahebganj'],
							['Dakuarhat-Uzirpur'],
							['Dhamura-Uzirpur'],
							['Jugirkanda-Uzirpur'],
							['Shikarpur-Uzirpur'],
							['Uzirpur-Uzirpur'],
							['Bhola Sadar-Bhola Sadar'],
							['Joynagar-Bhola Sadar'],
							['Borhanuddin UPO-Borhanuddin UPO'],
							['Mirzakalu-Borhanuddin UPO'],
							['Charfashion-Charfashion'],
							['Dularhat-Charfashion'],
							['Keramatganj-Charfashion'],
							['Doulatkhan-Doulatkhan'],
							['Hajipur-Doulatkhan'],
							['Hajirhat-Hajirhat'],
							['Hatshoshiganj-Hatshoshiganj'],
							['Daurihat-Lalmohan UPO'],
							['Gazaria-Lalmohan UPO'],
							['Lalmohan UPO-Lalmohan UPO'],
							['Baukathi-Jhalokathi Sadar'],
							['Gabha-Jhalokathi Sadar'],
							['Jhalokathi Sadar-Jhalokathi Sadar'],
							['Nabagram-Jhalokathi Sadar'],
							['Shekherhat-Jhalokathi Sadar'],
							['Amua-Kathalia'],
							['Kathalia-Kathalia'],
							['Niamatee-Kathalia'],
							['Shoulajalia-Kathalia'],
							['Beerkathi-Nalchhiti'],
							['Nalchhiti-Nalchhiti'],
							['Rajapur-Rajapur'],
							['Bagabandar-Bauphal'],
							['Bauphal-Bauphal'],
							['Birpasha-Bauphal'],
							['Kalaia-Bauphal'],
							['Kalishari-Bauphal'],
							['Dashmina-Dashmina'],
							['Galachipa-Galachipa'],
							['Gazipur Bandar-Galachipa'],
							['Khepupara-Khepupara'],
							['Mahipur-Khepupara'],
							['Dumkee-Patuakhali Sadar'],
							['Moukaran-Patuakhali Sadar'],
							['Patuakhali Sadar-Patuakhali Sadar'],
							['Rahimabad-Patuakhali Sadar'],
							['Subidkhali-Subidkhali'],
							['Banaripara-Banaripara'],
							['Chakhar-Banaripara'],
							['Bhandaria-Bhandaria'],
							['Dhaoa-Bhandaria'],
							['Kanudashkathi-Bhandaria'],
							['Jolagati-kaukhali'],
							['Joykul-kaukhali'],
							['Kaukhali-kaukhali'],
							['Keundia-kaukhali'],
							['Betmor Natun Hat-Mathbaria'],
							['Gulishakhali-Mathbaria'],
							['Halta-Mathbaria'],
							['Mathbaria-Mathbaria'],
							['Shilarganj-Mathbaria'],
							['Tiarkhali-Mathbaria'],
							['Tushkhali-Mathbaria'],
							['Nazirpur-Nazirpur'],
							['Sriramkathi-Nazirpur'],
							['Hularhat-Pirojpur Sadar'],
							['Parerhat-Pirojpur Sadar'],
							['Pirojpur Sadar-Pirojpur Sadar'],
							['Darus Sunnat-Swarupkathi'],
							['Jalabari-Swarupkathi'],
							['Kaurikhara-Swarupkathi'],
							['Swarupkathi-Swarupkathi'],
							['Alikadam-Alikadam'],
							['Bandarban Sadar-Bandarban Sadar'],
							['Naikhong-Naikhong'],
							['Roanchhari-Roanchhari'],
							['Ruma-Ruma'],
							['Lama-Thanchi'],
							['Thanchi-Thanchi'],
							['Akhaura-Akhaura'],
							['Azampur-Akhaura'],
							['Gangasagar-Akhaura'],
							['Banchharampur-Banchharampur'],
							['Ashuganj-Brahamanbaria Sadar'],
							['Ashuganj Share-Brahamanbaria Sadar'],
							['Brahamanbaria Sadar-Brahamanbaria Sadar'],
							['Poun-Brahamanbaria Sadar'],
							['Talshahar-Brahamanbaria Sadar'],
							['Chandidar-Kasba'],
							['Chargachh-Kasba'],
							['Gopinathpur-Kasba'],
							['Kasba-Kasba'],
							['Kuti-Kasba'],
							['Jibanganj-Nabinagar'],
							['Kaitala-Nabinagar'],
							['Laubfatehpur-Nabinagar'],
							['Nabinagar-Nabinagar'],
							['Rasullabad-Nabinagar'],
							['Ratanpur-Nabinagar'],
							['Salimganj-Nabinagar'],
							['Shahapur-Nabinagar'],
							['Shamgram-Nabinagar'],
							['Fandauk-Nasirnagar'],
							['Nasirnagar-Nasirnagar'],
							['Chandura-Sarail'],
							['Sarial-Sarail'],
							['Shahbajpur-Sarail'],
							['Baburhat-Chandpur Sadar'],
							['Chandpur Sadar-Chandpur Sadar'],
							['Puranbazar-Chandpur Sadar'],
							['Sahatali-Chandpur Sadar'],
							['Chandra-Faridganj'],
							['Faridganj-Faridganj'],
							['Gridkaliandia-Faridganj'],
							['Islampur Shah Isain -Faridganj'],
							['Rampurbazar-Faridganj'],
							['Rupsha-Faridganj'],
							['Bolakhal-Hajiganj'],
							['Hajiganj-Hajiganj'],
							['Gandamara-Hayemchar'],
							['Hayemchar-Hayemchar'],
							['Kachua-Kachua'],
							['Pak Shrirampur-Kachua'],
							['Rahima Nagar-Kachua'],
							['Shachar-Kachua'],
							['Kalipur-Matlobganj'],
							['Matlobganj-Matlobganj'],
							['Mohanpur-Matlobganj'],
							['Chotoshi-Shahrasti'],
							['Islamia Madrasha-Shahrasti'],
							['Khilabazar-Shahrasti'],
							['Pashchim Kherihar Al-Shahrasti'],
							['Shahrasti-Shahrasti'],
							['Anowara-Anawara'],
							['Battali-Anawara'],
							['Paroikora-Anawara'],
							['Boalkhali-Boalkhali'],
							['Charandwip-Boalkhali'],
							['Iqbal Park-Boalkhali'],
							['Kadurkhal-Boalkhali'],
							['Kanungopara-Boalkhali'],
							['Sakpura-Boalkhali'],
							['Saroatoli-Boalkhali'],
							['Al- Amin Baria Madra-Chittagong Sadar'],
							['Amin Jute Mills-Chittagong Sadar'],
							['Anandabazar-Chittagong Sadar'],
							['Bayezid Bostami-Chittagong Sadar'],
							['Chandgaon-Chittagong Sadar'],
							['Chawkbazar-Chittagong Sadar'],
							['Chitt. Cantonment-Chittagong Sadar'],
							['Chitt. Customs Acca-Chittagong Sadar'],
							['Chitt. Politechnic In-Chittagong Sadar'],
							['Chitt. Sailers Colon-Chittagong Sadar'],
							['Chittagong Airport-Chittagong Sadar'],
							['Chittagong Bandar-Chittagong Sadar'],
							['Chittagong GPO-Chittagong Sadar'],
							['Export Processing-Chittagong Sadar'],
							['Firozshah-Chittagong Sadar'],
							['Halishahar-Chittagong Sadar'],
							['Halishshar-Chittagong Sadar'],
							['Jalalabad-Chittagong Sadar'],
							['Jaldia Merine Accade-Chittagong Sadar'],
							['Middle Patenga-Chittagong Sadar'],
							['Mohard-Chittagong Sadar'],
							['North Halishahar-Chittagong Sadar'],
							['North Katuli-Chittagong Sadar'],
							['Pahartoli-Chittagong Sadar'],
							['Patenga-Chittagong Sadar'],
							['Rampura TSO-Chittagong Sadar'],
							['Wazedia-Chittagong Sadar'],
							['Barma-East Joara'],
							['Dohazari-East Joara'],
							['East Joara-East Joara'],
							['Gachbaria-East Joara'],
							['Bhandar Sharif-Fatikchhari'],
							['Fatikchhari-Fatikchhari'],
							['Harualchhari-Fatikchhari'],
							['Najirhat-Fatikchhari'],
							['Nanupur-Fatikchhari'],
							['Narayanhat-Fatikchhari'],
							['Chitt.University-Hathazari'],
							['Fatahabad-Hathazari'],
							['Gorduara-Hathazari'],
							['Hathazari-Hathazari'],
							['Katirhat-Hathazari'],
							['Madrasa-Hathazari'],
							['Mirzapur-Hathazari'],
							['Nuralibari-Hathazari'],
							['Yunus Nagar-Hathazari'],
							['Banigram-Jaldi'],
							['Gunagari-Jaldi'],
							['Jaldi-Jaldi'],
							['Khan Bahadur-Jaldi'],
							['Chunti-Lohagara'],
							['Lohagara-Lohagara'],
							['Padua-Lohagara'],
							['Abutorab-Mirsharai'],
							['Azampur-Mirsharai'],
							['Bharawazhat-Mirsharai'],
							['Darrogahat-Mirsharai'],
							['Joarganj-Mirsharai'],
							['Korerhat-Mirsharai'],
							['Mirsharai-Mirsharai'],
							['Mohazanhat-Mirsharai'],
							['Budhpara-Patia Head Office'],
							['Patia Head Office-Patia Head Office'],
							['Dhamair-Rangunia'],
							['Rangunia-Rangunia'],
							['B.I.T Post Office-Rouzan'],
							['Beenajuri-Rouzan'],
							['Dewanpur-Rouzan'],
							['Fatepur-Rouzan'],
							['Gahira-Rouzan'],
							['Guzra Noapara-Rouzan'],
							['jagannath Hat-Rouzan'],
							['Kundeshwari-Rouzan'],
							['Mohamuni-Rouzan'],
							['Rouzan-Rouzan'],
							['Sandwip-Sandwip'],
							['Shiberhat-Sandwip'],
							['Urirchar-Sandwip'],
							['Baitul Ijjat-Satkania'],
							['Bazalia-Satkania'],
							['Satkania-Satkania'],
							['Barabkunda-Sitakunda'],
							['Baroidhala-Sitakunda'],
							['Bawashbaria-Sitakunda'],
							['Bhatiari-Sitakunda'],
							['Fouzdarhat-Sitakunda'],
							['Jafrabad-Sitakunda'],
							['Kumira-Sitakunda'],
							['Sitakunda-Sitakunda'],
							['Barura-Barura'],
							['Murdafarganj-Barura'],
							['Poyalgachha-Barura'],
							['Brahmanpara-Brahmanpara'],
							['Burichang-Burichang'],
							['Maynamoti bazar-Burichang'],
							['Chandia-Chandina'],
							['Madhaiabazar-Chandina'],
							['Batisa-Chouddagram'],
							['Chiora-Chouddagram'],
							['Chouddagram-Chouddagram'],
							['Comilla Contoment-Comilla Sadar'],
							['Comilla Sadar-Comilla Sadar'],
							['Courtbari-Comilla Sadar'],
							['Halimanagar-Comilla Sadar'],
							['Suaganj-Comilla Sadar'],
							['Dashpara-Daudkandi'],
							['Daudkandi-Daudkandi'],
							['Eliotganj-Daudkandi'],
							['Gouripur-Daudkandi'],
							['Barashalghar-Davidhar'],
							['Davidhar-Davidhar'],
							['Dhamtee-Davidhar'],
							['Gangamandal-Davidhar'],
							['Homna-Homna'],
							['Bipulasar-Laksam'],
							['Laksam-Laksam'],
							['Lakshamanpur-Laksam'],
							['Chhariabazar-Langalkot'],
							['Dhalua-Langalkot'],
							['Gunabati-Langalkot'],
							['Langalkot-Langalkot'],
							['Bangra-Muradnagar'],
							['Companyganj-Muradnagar'],
							['Muradnagar-Muradnagar'],
							['Pantibazar-Muradnagar'],
							['Ramchandarpur-Muradnagar'],
							['Sonakanda-Muradnagar'],
							['Badarkali-Chiringga'],
							['Chiringga-Chiringga'],
							['Chiringga S.O-Chiringga'],
							['Malumghat-Chiringga'],
							['Coxs Bazar Sadar-Coxs Bazar Sadar'],
							['Eidga-Coxs Bazar Sadar'],
							['Zhilanja-Coxs Bazar Sadar'],
							['Gorakghat-Gorakghat'],
							['Kutubdia-Kutubdia'],
							['Ramu-Ramu'],
							['Hnila-Teknaf'],
							['St.Martin-Teknaf'],
							['Teknaf-Teknaf'],
							['Ukhia-Ukhia'],
							['Chhagalnaia-Chhagalnaia'],
							['Daraga Hat-Chhagalnaia'],
							['Maharajganj-Chhagalnaia'],
							['Puabashimulia-Chhagalnaia'],
							['Chhilonia-Dagonbhuia'],
							['Dagondhuia-Dagonbhuia'],
							['Dudmukha-Dagonbhuia'],
							['Rajapur-Dagonbhuia'],
							['Fazilpur-Feni Sadar'],
							['Feni Sadar-Feni Sadar'],
							['Laskarhat-Feni Sadar'],
							['Sharshadie-Feni Sadar'],
							['Fulgazi-Pashurampur'],
							['Munshirhat-Pashurampur'],
							['Pashurampur-Pashurampur'],
							['Shuarbazar-Pashurampur'],
							['Ahmadpur-Sonagazi'],
							['Kazirhat-Sonagazi'],
							['Motiganj-Sonagazi'],
							['Sonagazi-Sonagazi'],
							['Diginala-Diginala'],
							['Khagrachari Sadar-Khagrachari Sadar'],
							['Laxmichhari-Laxmichhari'],
							['Mahalchhari-Mahalchhari'],
							['Manikchhari-Manikchhari'],
							['Matiranga-Matiranga'],
							['Panchhari-Panchhari'],
							['Ramghar Head Office-Ramghar Head Office'],
							['Char Alexgander -Char Alexgander'],
							['Hajirghat-Char Alexgander'],
							['Ramgatirhat-Char Alexgander'],
							['Amani Lakshimpur-Lakshimpur Sadar'],
							['Bhabaniganj-Lakshimpur Sadar'],
							['Chandraganj-Lakshimpur Sadar'],
							['Choupalli-Lakshimpur Sadar'],
							['Dalal Bazar-Lakshimpur Sadar'],
							['Duttapara-Lakshimpur Sadar'],
							['Keramatganj-Lakshimpur Sadar'],
							['Lakshimpur Sadar-Lakshimpur Sadar'],
							['Mandari-Lakshimpur Sadar'],
							['Rupchara-Lakshimpur Sadar'],
							['Alipur-Ramganj'],
							['Dolta-Ramganj'],
							['Kanchanpur-Ramganj'],
							['Naagmud-Ramganj'],
							['Panpara-Ramganj'],
							['Ramganj-Ramganj'],
							['Bhuabari-Raypur'],
							['Haydarganj-Raypur'],
							['Nagerdighirpar-Raypur'],
							['Rakhallia-Raypur'],
							['Raypur-Raypur'],
							['Basur Hat-Basurhat'],
							['Charhajari-Basurhat'],
							['Alaiarpur-Begumganj'],
							['Amisha Para-Begumganj'],
							['Banglabazar-Begumganj'],
							['Bazra-Begumganj'],
							['Begumganj-Begumganj'],
							['Bhabani Jibanpur-Begumganj'],
							['Choumohani-Begumganj'],
							['Dauti-Begumganj'],
							['Durgapur-Begumganj'],
							['Gopalpur-Begumganj'],
							['Jamidar Hat-Begumganj'],
							['Joyag-Begumganj'],
							['Joynarayanpur-Begumganj'],
							['Khalafat Bazar-Begumganj'],
							['Khalishpur-Begumganj'],
							['Maheshganj-Begumganj'],
							['Mir Owarishpur-Begumganj'],
							['Nadona-Begumganj'],
							['Nandiapara-Begumganj'],
							['Oachhekpur-Begumganj'],
							['Rajganj-Begumganj'],
							['Sonaimuri-Begumganj'],
							['Tangirpar-Begumganj'],
							['Thanar Hat-Begumganj'],
							['Bansa Bazar-Chatkhil'],
							['Bodalcourt-Chatkhil'],
							['Chatkhil-Chatkhil'],
							['Dosh Gharia-Chatkhil'],
							['Karihati-Chatkhil'],
							['Khilpara-Chatkhil'],
							['Palla-Chatkhil'],
							['Rezzakpur-Chatkhil'],
							['Sahapur-Chatkhil'],
							['Sampara-Chatkhil'],
							['Shingbahura-Chatkhil'],
							['Solla-Chatkhil'],
							['Afazia-Hatiya'],
							['Hatiya-Hatiya'],
							['Tamoraddi-Hatiya'],
							['Chaprashir Hat-Noakhali Sadar'],
							['Char Jabbar-Noakhali Sadar'],
							['Charam Tua-Noakhali Sadar'],
							['Din Monir Hat-Noakhali Sadar'],
							['Kabirhat-Noakhali Sadar'],
							['Khalifar Hat-Noakhali Sadar'],
							['Mriddarhat-Noakhali Sadar'],
							['Noakhali College-Noakhali Sadar'],
							['Noakhali Sadar-Noakhali Sadar'],
							['Pak Kishoreganj-Noakhali Sadar'],
							['Sonapur-Noakhali Sadar'],
							['Beezbag-Senbag'],
							['Chatarpaia-Senbag'],
							['Kallyandi-Senbag'],
							['Kankirhat-Senbag'],
							['Senbag-Senbag'],
							['T.P. Lamua-Senbag'],
							['Barakal-Barakal'],
							['Bilaichhari-Bilaichhari'],
							['Jarachhari-Jarachhari'],
							['Betbunia-Kalampati'],
							['Kalampati-Kalampati'],
							['Chandraghona-kaptai'],
							['Kaptai-kaptai'],
							['Kaptai Nuton Bazar-kaptai'],
							['Kaptai Project-kaptai'],
							['Longachh-Longachh'],
							['Marishya-Marishya'],
							['Nanichhar-Naniachhar'],
							['Rajsthali-Rajsthali'],
							['Rangamati Sadar-Rangamati Sadar'],
							['Demra-Demra'],
							['Matuail-Demra'],
							['Sarulia-Demra'],
							['Dhaka CantonmentTSO-Dhaka Cantt.'],
							['Dhamrai-Dhamrai'],
							['Kamalpur-Dhamrai'],
							['Jigatala TSO-Dhanmondi'],
							['Banani TSO-Gulshan'],
							['Gulshan Model Town -Gulshan'],
							['Dhania TSO-Jatrabari'],
							['Joypara-Joypara'],
							['Narisha-Joypara'],
							['Palamganj-Joypara'],
							['Ati-Keraniganj'],
							['Dhaka Jute Mills-Keraniganj'],
							['Kalatia-Keraniganj'],
							['Keraniganj-Keraniganj'],
							['KhilgaonTSO-Khilgaon'],
							['KhilkhetTSO-Khilkhet'],
							['Posta TSO-Lalbag'],
							['Mirpur TSO-Mirpur'],
							['Mohammadpur Housing -Mohammadpur'],
							['Sangsad BhabanTSO-Mohammadpur'],
							['BangabhabanTSO-Motijheel'],
							['DilkushaTSO-Motijheel'],
							['Agla-Nawabganj'],
							['Churain-Nawabganj'],
							['Daudpur-Nawabganj'],
							['Hasnabad-Nawabganj'],
							['Khalpar-Nawabganj'],
							['Nawabganj-Nawabganj'],
							['New Market TSO-New market'],
							['Dhaka GPO-Palton'],
							['Shantinagr TSO-Ramna'],
							['Basabo TSO-Sabujbag'],
							['Amin Bazar-Savar'],
							['Dairy Farm-Savar'],
							['EPZ-Savar'],
							['Jahangirnagar Univer-Savar'],
							['Kashem Cotton Mills-Savar'],
							['Rajphulbaria-Savar'],
							['Savar-Savar'],
							['Savar Canttonment-Savar'],
							['Saver P.A.T.C-Savar'],
							['Shimulia-Savar'],
							['Dhaka Sadar HO-Sutrapur'],
							['Gendaria TSO-Sutrapur'],
							['Wari TSO-Sutrapur'],
							['Tejgaon TSO-Tejgaon'],
							['Dhaka Politechnic -Tejgaon Industrial Area'],
							['Uttara Model TwonTSO-Uttara'],
							['Alfadanga-Alfadanga'],
							['Bhanga-Bhanga'],
							['Boalmari-Boalmari'],
							['Rupatpat-Boalmari'],
							['Charbadrashan-Charbhadrasan'],
							['Ambikapur-Faridpur Sadar'],
							['Baitulaman Politecni-Faridpur Sadar'],
							['Faridpursadar-Faridpur Sadar'],
							['Kanaipur-Faridpur Sadar'],
							['Kamarkali-Madukhali'],
							['Madukhali-Madukhali'],
							['Nagarkanda-Nagarkanda'],
							['Talma-Nagarkanda'],
							['Bishwa jaker Manjil-Sadarpur'],
							['Hat Krishapur-Sadarpur'],
							['Sadarpur-Sadarpur'],
							['Shriangan-Shriangan'],
							['B.O.F-Gazipur Sadar'],
							['B.R.R-Gazipur Sadar'],
							['Chandna-Gazipur Sadar'],
							['Gazipur Sadar-Gazipur Sadar'],
							['National University-Gazipur Sadar'],
							['Kaliakaar-Kaliakaar'],
							['Safipur-Kaliakaar'],
							['Kaliganj-Kaliganj'],
							['Pubail-Kaliganj'],
							['Santanpara-Kaliganj'],
							['Vaoal Jamalpur-Kaliganj'],
							['kapashia-Kapashia'],
							['Ershad Nagar-Monnunagar'],
							['Monnunagar-Monnunagar'],
							['Nishat Nagar-Monnunagar'],
							['Barmi-Sreepur'],
							['Bashamur-Sreepur'],
							['Boubi-Sreepur'],
							['Kawraid-Sreepur'],
							['Satkhamair-Sreepur'],
							['Sreepur-Sreepur'],
							['Rajendrapur-Sripur'],
							['Rajendrapur Canttome-Sripur'],
							['Barfa-Gopalganj Sadar'],
							['Chandradighalia-Gopalganj Sadar'],
							['Gopalganj Sadar-Gopalganj Sadar'],
							['Ulpur-Gopalganj Sadar'],
							['Jonapur-Kashiani'],
							['Kashiani-Kashiani'],
							['Ramdia College-Kashiani'],
							['Ratoil-Kashiani'],
							['Kotalipara-Kotalipara'],
							['Batkiamari-Maksudpur'],
							['Khandarpara-Maksudpur'],
							['Maksudpur-Maksudpur'],
							['Patgati-Tungipara'],
							['Tungipara-Tungipara'],
							['Dewangonj-Dewangonj'],
							['Dewangonj S. Mills-Dewangonj'],
							['Durmoot-Islampur'],
							['Gilabari-Islampur'],
							['Islampur-Islampur'],
							['Jamalpur-Jamalpur'],
							['Nandina-Jamalpur'],
							['Narundi-Jamalpur'],
							['Jamalpur-Malandah'],
							['Mahmoodpur-Malandah'],
							['Malancha-Malandah'],
							['Malandah-Malandah'],
							['Balijhuri-Mathargonj'],
							['Mathargonj-Mathargonj'],
							['Bausee-Shorishabari'],
							['Gunerbari-Shorishabari'],
							['Jagannath Ghat-Shorishabari'],
							['Jamuna Sar Karkhana-Shorishabari'],
							['Pingna-Shorishabari'],
							['Shorishabari-Shorishabari'],
							['Bajitpur-Bajitpur'],
							['Laksmipur-Bajitpur'],
							['Sararchar-Bajitpur'],
							['Bhairab-Bhairob'],
							['Hossenpur-Hossenpur'],
							['Itna-Itna'],
							['Karimganj-Karimganj'],
							['Gochhihata-Katiadi'],
							['Katiadi-Katiadi'],
							['Kishoreganj S.Mills-Kishoreganj Sadar'],
							['Kishoreganj Sadar-Kishoreganj Sadar'],
							['Maizhati-Kishoreganj Sadar'],
							['Nilganj-Kishoreganj Sadar'],
							['Chhoysuti-Kuliarchar'],
							['Kuliarchar-Kuliarchar'],
							['Abdullahpur-Mithamoin'],
							['MIthamoin-Mithamoin'],
							['Nikli-Nikli'],
							['Ostagram-Ostagram'],
							['Pakundia-Pakundia'],
							['Tarial-Tarial'],
							['Bahadurpur-Barhamganj'],
							['Barhamganj-Barhamganj'],
							['Nilaksmibandar-Barhamganj'],
							['Umedpur-Barhamganj'],
							['Kalkini-kalkini'],
							['Sahabrampur-kalkini'],
							['Charmugria-Madaripur Sadar'],
							['Habiganj-Madaripur Sadar'],
							['Kulpaddi-Madaripur Sadar'],
							['Madaripur Sadar-Madaripur Sadar'],
							['Mustafapur-Madaripur Sadar'],
							['Khalia-Rajoir'],
							['Rajoir-Rajoir'],
							['Doulatpur-Doulatpur'],
							['Gheor-Gheor'],
							['Jhitka-Lechhraganj'],
							['Lechhraganj-Lechhraganj'],
							['Barangail-Manikganj Sadar'],
							['Gorpara-Manikganj Sadar'],
							['Mahadebpur-Manikganj Sadar'],
							['Manikganj Bazar-Manikganj Sadar'],
							['Manikganj Sadar-Manikganj Sadar'],
							['Baliati-Saturia'],
							['Saturia-Saturia'],
							['Aricha-Shibloya'],
							['Shibaloy-Shibloya'],
							['Tewta-Shibloya'],
							['Uthli-Shibloya'],
							['Baira-Singari'],
							['joymantop-Singari'],
							['Singair-Singari'],
							['Gajaria-Gajaria'],
							['Hossendi-Gajaria'],
							['Rasulpur-Gajaria'],
							['Gouragonj-Lohajong'],
							['Gouragonj-Lohajong'],
							['Haldia SO-Lohajong'],
							['Haridia-Lohajong'],
							['Haridia DESO-Lohajong'],
							['Korhati-Lohajong'],
							['Lohajang-Lohajong'],
							['Madini Mandal-Lohajong'],
							['Medini Mandal EDSO-Lohajong'],
							['Kathakhali-Munshiganj Sadar'],
							['Mirkadim-Munshiganj Sadar'],
							['Munshiganj Sadar-Munshiganj Sadar'],
							['Rikabibazar-Munshiganj Sadar'],
							['Ichapur-Sirajdikhan'],
							['Kola-Sirajdikhan'],
							['Malkha Nagar-Sirajdikhan'],
							['Shekher Nagar-Sirajdikhan'],
							['Sirajdikhan-Sirajdikhan'],
							['Baghra-Srinagar'],
							['Barikhal-Srinagar'],
							['Bhaggyakul-Srinagar'],
							['Hashara-Srinagar'],
							['Kolapara-Srinagar'],
							['Kumarbhog-Srinagar'],
							['Mazpara-Srinagar'],
							['Srinagar-Srinagar'],
							['Vaggyakul SO-Srinagar'],
							['Bajrajugini-Tangibari'],
							['Baligao-Tangibari'],
							['Betkahat-Tangibari'],
							['Dighirpar-Tangibari'],
							['Hasail-Tangibari'],
							['Pura-Tangibari'],
							['Pura EDSO-Tangibari'],
							['Tangibari-Tangibari'],
							['Bhaluka-Bhaluka'],
							['Fulbaria-Fulbaria'],
							['Duttarbazar-Gaforgaon'],
							['Gaforgaon-Gaforgaon'],
							['Kandipara-Gaforgaon'],
							['Shibganj-Gaforgaon'],
							['Usti-Gaforgaon'],
							['Gouripur-Gouripur'],
							['Ramgopalpur-Gouripur'],
							['Dhara-Haluaghat'],
							['Haluaghat-Haluaghat'],
							['Munshirhat-Haluaghat'],
							['Atharabari-Isshwargonj'],
							['Isshwargonj-Isshwargonj'],
							['Sohagi-Isshwargonj'],
							['Muktagachha-Muktagachha'],
							['Agriculture Universi-Mymensingh Sadar'],
							['Biddyaganj-Mymensingh Sadar'],
							['Kawatkhali-Mymensingh Sadar'],
							['Mymensingh Sadar-Mymensingh Sadar'],
							['Pearpur-Mymensingh Sadar'],
							['Shombhuganj-Mymensingh Sadar'],
							['Gangail-Nandail'],
							['Nandail-Nandail'],
							['Beltia-Phulpur'],
							['Phulpur-Phulpur'],
							['Tarakanda-Phulpur'],
							['Ahmadbad-Trishal'],
							['Dhala-Trishal'],
							['Ram Amritaganj-Trishal'],
							['Trishal-Trishal'],
							['Araihazar-Araihazar'],
							['Gopaldi-Araihazar'],
							['Baidder Bazar-Baidder Bazar'],
							['Bara Nagar-Baidder Bazar'],
							['Barodi-Baidder Bazar'],
							['Bandar-Bandar'],
							['BIDS-Bandar'],
							['D.C Mills-Bandar'],
							['Madanganj-Bandar'],
							['Nabiganj-Bandar'],
							['Fatulla Bazar-Fatullah'],
							['Fatullah-Fatullah'],
							['Narayanganj Sadar-Narayanganj Sadar'],
							['Bhulta-Rupganj'],
							['Kanchan-Rupganj'],
							['Murapara-Rupganj'],
							['Nagri-Rupganj'],
							['Rupganj-Rupganj'],
							['Adamjeenagar-Siddirganj'],
							['LN Mills-Siddirganj'],
							['Siddirganj-Siddirganj'],
							['Belabo-Belabo'],
							['Hatirdia-Monohordi'],
							['Katabaria-Monohordi'],
							['Monohordi-Monohordi'],
							['Karimpur-Narshingdi Sadar'],
							['Madhabdi-Narshingdi Sadar'],
							['Narshingdi College-Narshingdi Sadar'],
							['Narshingdi Sadar-Narshingdi Sadar'],
							['Panchdona-Narshingdi Sadar'],
							['UMC Jute Mills-Narshingdi Sadar'],
							['Char Sindhur-Palash'],
							['Ghorashal-Palash'],
							['Ghorashal Urea Facto-Palash'],
							['Palash-Palash'],
							['Bazar Hasnabad-Raypura'],
							['Radhaganj bazar-Raypura'],
							['Raypura-Raypura'],
							['Shibpur-Shibpur'],
							['Susnng Durgapur- Susung Durgapur'],
							['Atpara-Atpara'],
							['Barhatta-Barhatta'],
							['Dharampasha-Dharmapasha'],
							['Dhobaura-Dhobaura'],
							['Sakoai-Dhobaura'],
							['Kalmakanda-Kalmakanda'],
							['Kendua-Kendua'],
							['Khaliajhri-Khaliajuri'],
							['Shaldigha-Khaliajuri'],
							['Madan-Madan'],
							['Moddoynagar-Moddhynagar'],
							['Mohanganj-Mohanganj'],
							['Baikherhati-Netrakona Sadar'],
							['Netrakona Sadar-Netrakona Sadar'],
							['Jaria Jhanjhail-Purbadhola'],
							['Purbadhola-Purbadhola'],
							['Shamgonj-Purbadhola'],
							['Baliakandi-Baliakandi'],
							['Nalia-Baliakandi'],
							['Mrigibazar-Pangsha'],
							['Pangsha-Pangsha'],
							['Ramkol-Pangsha'],
							['Ratandia-Pangsha'],
							['Goalanda-Rajbari Sadar'],
							['Khankhanapur-Rajbari Sadar'],
							['Rajbari Sadar-Rajbari Sadar'],
							['Bhedorganj-Bhedorganj'],
							['Damudhya-Damudhya'],
							['Gosairhat-Gosairhat'],
							['Jajira-Jajira'],
							['Bhozeshwar-Naria'],
							['Gharisar-Naria'],
							['Kartikpur-Naria'],
							['Naria-Naria'],
							['Upshi-Naria'],
							['Angaria-Shariatpur Sadar'],
							['Chikandi-Shariatpur Sadar'],
							['Shariatpur Sadar-Shariatpur Sadar'],
							['Bakshigonj-Bakshigonj'],
							['Jhinaigati-Jhinaigati'],
							['Gonopaddi-Nakla'],
							['Nakla-Nakla'],
							['Hatibandha-Nalitabari'],
							['Nalitabari-Nalitabari'],
							['Sherpur Shadar-Sherpur Shadar'],
							['Shribardi-Shribardi'],
							['Basail-Basail'],
							['Bhuapur-Bhuapur'],
							['Delduar-Delduar'],
							['Elasin-Delduar'],
							['Hinga Nagar-Delduar'],
							['Jangalia-Delduar'],
							['Lowhati-Delduar'],
							['Patharail-Delduar'],
							['D. Pakutia-Ghatail'],
							['Dhalapara-Ghatail'],
							['Ghatial-Ghatail'],
							['Lohani-Ghatail'],
							['Zahidganj-Ghatail'],
							['Gopalpur-Gopalpur'],
							['Hemnagar-Gopalpur'],
							['Jhowail-Gopalpur'],
							['Ballabazar-Kalihati'],
							['Elinga-Kalihati'],
							['Kalihati-Kalihati'],
							['Nagarbari-Kalihati'],
							['Nagarbari SO-Kalihati'],
							['Nagbari-Kalihati'],
							['Palisha-Kalihati'],
							['Rajafair-Kalihati'],
							['Kashkawlia-Kashkaolia'],
							['Dhobari-Madhupur'],
							['Madhupur-Madhupur'],
							['Gorai-Mirzapur'],
							['Jarmuki-Mirzapur'],
							['M.C. College-Mirzapur'],
							['Mirzapur-Mirzapur'],
							['Mohera-Mirzapur'],
							['Warri paikpara-Mirzapur'],
							['Dhuburia-Nagarpur'],
							['Nagarpur-Nagarpur'],
							['Salimabad-Nagarpur'],
							['Kochua-Sakhipur'],
							['Sakhipur-Sakhipur'],
							['Kagmari-Tangail Sadar'],
							['Korotia-Tangail Sadar'],
							['Purabari-Tangail Sadar'],
							['Santosh-Tangail Sadar'],
							['Tangail Sadar-Tangail Sadar'],
							['Alamdanga-Alamdanga'],
							['Hardi-Alamdanga'],
							['Chuadanga Sadar-Chuadanga Sadar'],
							['Munshiganj-Chuadanga Sadar'],
							['Andulbaria-Damurhuda'],
							['Damurhuda-Damurhuda'],
							['Darshana-Damurhuda'],
							['Doulatganj-Doulatganj'],
							['Bagerhat Sadar-Bagerhat Sadar'],
							['P.C College-Bagerhat Sadar'],
							['Rangdia-Bagerhat Sadar'],
							['Chalna Ankorage-Chalna Ankorage'],
							['Mongla Port-Chalna Ankorage'],
							['Barabaria-Chitalmari'],
							['Chitalmari-Chitalmari'],
							['Bhanganpar Bazar-Fakirhat'],
							['Fakirhat-Fakirhat'],
							['Mansa-Fakirhat'],
							['Kachua-Kachua UPO'],
							['Sonarkola-Kachua UPO'],
							['Charkulia-Mollahat'],
							['Dariala-Mollahat'],
							['Kahalpur-Mollahat'],
							['Mollahat-Mollahat'],
							['Nagarkandi-Mollahat'],
							['Pak Gangni-Mollahat'],
							['Morelganj-Morelganj'],
							['Sannasi Bazar-Morelganj'],
							['Telisatee-Morelganj'],
							['Foylahat-Rampal'],
							['Gourambha-Rampal'],
							['Rampal-Rampal'],
							['Sonatunia-Rampal'],
							['Rayenda-Rayenda'],
							['Bagharpara-Bagharpara'],
							['Gouranagar-Bagharpara'],
							['Chougachha-Chaugachha'],
							['Basundia-Jessore Sadar'],
							['Chanchra-Jessore Sadar'],
							['Churamankathi-Jessore Sadar'],
							['Jessore Airbach-Jessore Sadar'],
							['Jessore canttonment-Jessore Sadar'],
							['Jessore Sadar-Jessore Sadar'],
							['Jessore Upa-Shahar-Jessore Sadar'],
							['Rupdia-Jessore Sadar'],
							['Jhikargachha-Jhikargachha'],
							['Keshobpur-Keshabpur'],
							['Monirampur-Monirampur'],
							['Bhugilhat-Noapara'],
							['Noapara-Noapara'],
							['Rajghat-Noapara'],
							['Bag Achra-Sarsa'],
							['Benapole-Sarsa'],
							['Jadabpur-Sarsa'],
							['Sarsa-Sarsa'],
							['Harinakundu-Harinakundu'],
							['Jinaidaha Cadet College-Jinaidaha Sadar'],
							['Jinaidaha Sadar-Jinaidaha Sadar'],
							['Kotchandpur-Kotchandpur'],
							['Maheshpur-Maheshpur'],
							['Hatbar Bazar-Naldanga'],
							['Naldanga-Naldanga'],
							['Kumiradaha-Shailakupa'],
							['Shailakupa-Shailakupa'],
							['Alaipur-Alaipur'],
							['Belphulia-Alaipur'],
							['Rupsha-Alaipur'],
							['Batiaghat-Batiaghat'],
							['Surkalee-Batiaghat'],
							['Bajua-Chalna Bazar'],
							['Chalna Bazar-Chalna Bazar'],
							['Dakup-Chalna Bazar'],
							['Nalian-Chalna Bazar'],
							['Chandni Mahal-Digalia'],
							['Digalia-Digalia'],
							['Gazirhat-Digalia'],
							['Ghoshghati-Digalia'],
							['Senhati-Digalia'],
							['Atra Shilpa Area-Khulna Sadar'],
							['BIT Khulna-Khulna Sadar'],
							['Doulatpur-Khulna Sadar'],
							['Jahanabad Canttonmen-Khulna Sadar'],
							['Khula Sadar-Khulna Sadar'],
							['Khulna G.P.O-Khulna Sadar'],
							['Khulna Shipyard-Khulna Sadar'],
							['Khulna University-Khulna Sadar'],
							['Siramani-Khulna Sadar'],
							['Sonali Jute Mills-Khulna Sadar'],
							['Amadee-Madinabad'],
							['Madinabad-Madinabad'],
							['Chandkhali-Paikgachha'],
							['Garaikhali-Paikgachha'],
							['Godaipur-Paikgachha'],
							['Kapilmoni-Paikgachha'],
							['Katipara-Paikgachha'],
							['Paikgachha-Paikgachha'],
							['Phultala-Phultala'],
							['Chuknagar-Sajiara'],
							['Ghonabanda-Sajiara'],
							['Sajiara-Sajiara'],
							['Shahapur-Sajiara'],
							['Pak Barasat-Terakhada'],
							['Terakhada-Terakhada'],
							['Allardarga-Bheramara'],
							['Bheramara-Bheramara'],
							['Ganges Bheramara-Bheramara'],
							['Janipur-Janipur'],
							['Khoksa-Janipur'],
							['Kumarkhali-Kumarkhali'],
							['Panti-Kumarkhali'],
							['Islami University-Kustia Sadar'],
							['Jagati-Kustia Sadar'],
							['Kushtia Mohini-Kustia Sadar'],
							['Kustia Sadar-Kustia Sadar'],
							['Amla Sadarpur-Mirpur'],
							['Mirpur-Mirpur'],
							['Poradaha-Mirpur'],
							['Khasmathurapur-Rafayetpur'],
							['Rafayetpur-Rafayetpur'],
							['Taragunia-Rafayetpur'],
							['Arpara-Arpara'],
							['Magura Sadar-Magura Sadar'],
							['Binodpur-Mohammadpur'],
							['Mohammadpur-Mohammadpur'],
							['Nahata-Mohammadpur'],
							['Langalbadh-Shripur'],
							['Nachol-Shripur'],
							['Shripur-Shripur'],
							['Gangni-Gangni'],
							['Amjhupi-Meherpur Sadar'],
							['Amjhupi-Meherpur Sadar'],
							['Meherpur Sadar-Meherpur Sadar'],
							['Mujib Nagar Complex-Meherpur Sadar'],
							['Kalia-Kalia'],
							['Baradia-Laxmipasha'],
							['Itna-Laxmipasha'],
							['Laxmipasha-Laxmipasha'],
							['Lohagora-Laxmipasha'],
							['Naldi-Laxmipasha'],
							['Mohajan-Mohajan'],
							['Narail Sadar-Narail Sadar'],
							['Ratanganj-Narail Sadar'],
							['Ashashuni-Ashashuni'],
							['Baradal-Ashashuni'],
							['Debbhata-Debbhata'],
							['Gurugram-Debbhata'],
							['Chandanpur-kalaroa'],
							['Hamidpur-kalaroa'],
							['Jhaudanga-kalaroa'],
							['kalaroa-kalaroa'],
							['Khordo-kalaroa'],
							['Murarikati-kalaroa'],
							['Kaliganj UPO-Kaliganj UPO'],
							['Nalta Mubaroknagar-Kaliganj UPO'],
							['Ratanpur -Kaliganj UPO'],
							['Buri Goalini-Nakipur'],
							['Gabura-Nakipur'],
							['Habinagar-Nakipur'],
							['Nakipur-Nakipur'],
							['Naobeki-Nakipur'],
							['Noornagar-Nakipur'],
							['Budhhat-Satkhira Sadar'],
							['Gunakar kati-Satkhira Sadar'],
							['Satkhira Islamia Acc-Satkhira Sadar'],
							['Satkhira Sadar-Satkhira Sadar'],
							['Patkelghata-Taala'],
							['Taala-Taala'],
							['Adamdighi-Alamdighi'],
							['Nasharatpur-Alamdighi'],
							['Santahar-Alamdighi'],
							['Bogra Canttonment-Bogra Sadar'],
							['Bogra Sadar-Bogra Sadar'],
							['Dhunat-Dhunat'],
							['Gosaibari-Dhunat'],
							['Dupchachia-Dupchachia'],
							['Talora-Dupchachia'],
							['Gabtoli-Gabtoli'],
							['Sukhanpukur-Gabtoli'],
							['Kahalu-Kahalu'],
							['Nandigram-Nandigram'],
							['Chandan Baisha-Sariakandi'],
							['Sariakandi-Sariakandi'],
							['Chandaikona-Sherpur'],
							['Palli Unnyan Accadem-Sherpur'],
							['Sherpur-Sherpur'],
							['Shibganj-Shibganj'],
							['Sonatola-Sonatola'],
							['Bholahat-Bholahat'],
							['Amnura-Chapinawabganj Sadar'],
							['Chapinawbganj Sadar-Chapinawabganj Sadar'],
							['Rajarampur-Chapinawabganj Sadar'],
							['Ramchandrapur-Chapinawabganj Sadar'],
							['Mandumala-Nachol'],
							['Nachol-Nachol'],
							['Gomashtapur-Rohanpur'],
							['Rohanpur-Rohanpur'],
							['Kansart-Shibganj U.P.O'],
							['Manaksha-Shibganj U.P.O'],
							['Shibganj U.P.O-Shibganj U.P.O'],
							['Akklepur-Akkelpur'],
							['jamalganj-Akkelpur'],
							['Tilakpur-Akkelpur'],
							['Joypurhat Sadar-Joypurhat Sadar'],
							['kalai-kalai'],
							['Khetlal-Khetlal'],
							['Panchbibi-panchbibi'],
							['Ahsanganj-Ahsanganj'],
							['Bandai-Ahsanganj'],
							['Badalgachhi-Badalgachhi'],
							['Dhamuirhat-Dhamuirhat'],
							['Mahadebpur-Mahadebpur'],
							['Naogaon Sadar-Naogaon Sadar'],
							['Niamatpur-Niamatpur'],
							['Nitpur-Nitpur'],
							['Panguria-Nitpur'],
							['Porsa-Nitpur'],
							['Patnitala-Patnitala'],
							['Balihar-Prasadpur'],
							['Manda-Prasadpur'],
							['Prasadpur-Prasadpur'],
							['Kashimpur-Raninagar'],
							['Raninagar-Raninagar'],
							['Moduhil-Sapahar'],
							['Sapahar-Sapahar'],
							['Abdulpur-Gopalpur UPO'],
							['Gopalpur U.P.O-Gopalpur UPO'],
							['Lalpur S.O-Gopalpur UPO'],
							['Baraigram-Harua'],
							['Dayarampur-Harua'],
							['Harua-Harua'],
							['Hatgurudaspur-Hatgurudaspur'],
							['Laxman-Laxman'],
							['Baiddyabal Gharia-Natore Sadar'],
							['Digapatia-Natore Sadar'],
							['Madhnagar-Natore Sadar'],
							['Natore Sadar-Natore Sadar'],
							['Singra-Singra'],
							['Banwarinagar-Banwarinagar'],
							['Bera-Bera'],
							['Kashinathpur-Bera'],
							['Nakalia-Bera'],
							['Puran Bharenga-Bera'],
							['Bhangura-Bhangura'],
							['Chatmohar-Chatmohar'],
							['Debottar-Debottar'],
							['Dhapari-Ishwardi'],
							['Ishwardi-Ishwardi'],
							['Pakshi-Ishwardi'],
							['Rajapur-Ishwardi'],
							['Hamayetpur-Pabna Sadar'],
							['Kaliko Cotton Mills-Pabna Sadar'],
							['Pabna Sadar-Pabna Sadar'],
							['Sathia-Sathia'],
							['Sagarkandi-Sujanagar'],
							['Sujanagar-Sujanagar'],
							['Arani-Bagha'],
							['Bagha-Bagha'],
							['Bhabaniganj-Bhabaniganj'],
							['Taharpur-Bhabaniganj'],
							['Charghat-Charghat'],
							['Sarda-Charghat'],
							['Durgapur-Durgapur'],
							['Godagari-Godagari'],
							['Premtoli-Godagari'],
							['Khodmohanpur-Khod Mohanpur'],
							['Lalitganj-Lalitganj'],
							['Rajshahi Sugar Mills-Lalitganj'],
							['Shyampur-Lalitganj'],
							['Putia-Putia'],
							['Binodpur Bazar-Rajshahi Sadar'],
							['Ghuramara-Rajshahi Sadar'],
							['Kazla-Rajshahi Sadar'],
							['Rajshahi Canttonment-Rajshahi Sadar'],
							['Rajshahi Court-Rajshahi Sadar'],
							['Rajshahi Sadar-Rajshahi Sadar'],
							['Rajshahi University-Rajshahi Sadar'],
							['Sapura-Rajshahi Sadar'],
							['Tanor-Tanor'],
							['Baiddya Jam Toil-Baiddya Jam Toil'],
							['Belkuchi-Belkuchi'],
							['Enayetpur-Belkuchi'],
							['Rajapur-Belkuchi'],
							['Sohagpur-Belkuchi'],
							['Sthal-Belkuchi'],
							['Dhangora-Dhangora'],
							['Malonga-Dhangora'],
							['Gandail-Kazipur'],
							['Kazipur-Kazipur'],
							['Shuvgachha-Kazipur'],
							['Jamirta-Shahjadpur'],
							['Kaijuri-Shahjadpur'],
							['Porjana-Shahjadpur'],
							['Shahjadpur-Shahjadpur'],
							['Raipur-Sirajganj Sadar'],
							['Rashidabad-Sirajganj Sadar'],
							['Sirajganj Sadar-Sirajganj Sadar'],
							['Tarash-Tarash'],
							['Lahiri Mohanpur-Ullapara'],
							['Salap-Ullapara'],
							['Ullapara-Ullapara'],
							['Ullapara R.S-Ullapara'],
							['Azmireeganj-Azmireeganj'],
							['Bahubal-Bahubal'],
							['Baniachang-Baniachang'],
							['Jatrapasha-Baniachang'],
							['Kadirganj-Baniachang'],
							['Chandpurbagan-Chunarughat'],
							['Chunarughat-Chunarughat'],
							['Narapati-Chunarughat'],
							['Gopaya-Hobiganj Sadar'],
							['Hobiganj Sadar-Hobiganj Sadar'],
							['Shaestaganj-Hobiganj Sadar'],
							['Kalauk-Kalauk'],
							['Lakhai-Kalauk'],
							['Itakhola-Madhabpur'],
							['Madhabpur-Madhabpur'],
							['Saihamnagar-Madhabpur'],
							['Shahajibazar-Madhabpur'],
							['Digalbak-Nabiganj'],
							['Golduba-Nabiganj'],
							['Goplarbazar-Nabiganj'],
							['Inathganj-Nabiganj'],
							['Nabiganj-Nabiganj'],
							['Baralekha-Baralekha'],
							['Dhakkhinbag-Baralekha'],
							['Juri-Baralekha'],
							['Purbashahabajpur-Baralekha'],
							['Kamalganj-Kamalganj'],
							['Keramatnaga-Kamalganj'],
							['Munshibazar-Kamalganj'],
							['Patrakhola-Kamalganj'],
							['Shamsher Nagar-Kamalganj'],
							['Baramchal-Kulaura'],
							['Kajaldhara-Kulaura'],
							['Karimpur-Kulaura'],
							['Kulaura-Kulaura'],
							['Langla-Kulaura'],
							['Prithimpasha-Kulaura'],
							['Tillagaon-Kulaura'],
							['Afrozganj-Moulvibazar Sadar'],
							['Barakapan-Moulvibazar Sadar'],
							['Monumukh-Moulvibazar Sadar'],
							['Moulvibazar Sadar-Moulvibazar Sadar'],
							['Rajnagar-Rajnagar'],
							['Kalighat-Srimangal'],
							['Khejurichhara-Srimangal'],
							['Narain Chora-Srimangal'],
							['Satgaon-Srimangal'],
							['Srimangal-Srimangal'],
							['Bishamsapur-Bishamsarpur'],
							['Chhatak-Chhatak'],
							['Chhatak Cement Facto-Chhatak'],
							['Chhatak Paper Mills-Chhatak'],
							['Chourangi Bazar-Chhatak'],
							['Gabindaganj-Chhatak'],
							['Gabindaganj Natun Ba-Chhatak'],
							['Islamabad-Chhatak'],
							['jahidpur-Chhatak'],
							['Khurma-Chhatak'],
							['Moinpur-Chhatak'],
							['Dhirai Chandpur-Dhirai Chandpur'],
							['Jagdal-Dhirai Chandpur'],
							['Duara bazar-Duara bazar'],
							['Ghungiar-Ghungiar'],
							['Atuajan-Jagnnathpur'],
							['Hasan Fatemapur-Jagnnathpur'],
							['Jagnnathpur-Jagnnathpur'],
							['Rasulganj-Jagnnathpur'],
							['Shiramsi-Jagnnathpur'],
							['Syedpur-Jagnnathpur'],
							['Sachna-Sachna'],
							['Pagla-Sunamganj Sadar'],
							['Patharia-Sunamganj Sadar'],
							['Sunamganj Sadar-Sunamganj Sadar'],
							['Tahirpur-Tahirpur'],
							['Balaganj-Balaganj'],
							['Begumpur-Balaganj'],
							['Brahman Shashon-Balaganj'],
							['Gaharpur-Balaganj'],
							['Goala Bazar-Balaganj'],
							['Karua-Balaganj'],
							['Kathal Khair-Balaganj'],
							['Natun Bazar-Balaganj'],
							['Omarpur-Balaganj'],
							['Tajpur-Balaganj'],
							['Bianibazar-Bianibazar'],
							['Churkai -Bianibazar'],
							['jaldup-Bianibazar'],
							['Kurar bazar-Bianibazar'],
							['Mathiura-Bianibazar'],
							['Salia bazar-Bianibazar'],
							['Bishwanath-Bishwanath'],
							['Dashghar-Bishwanath'],
							['Deokalas-Bishwanath'],
							['Doulathpur-Bishwanath'],
							['Singer kanch-Bishwanath'],
							['Fenchuganj-Fenchuganj'],
							['Fenchuganj SareKarkh-Fenchuganj'],
							['Chiknagul-Goainhat'],
							['Goainhat-Goainhat'],
							['Jaflong-Goainhat'],
							['banigram-Gopalganj'],
							['Chandanpur-Gopalganj'],
							['Dakkhin Bhadashore-Gopalganj'],
							['Dhaka Dakkhin-Gopalganj'],
							['Gopalgannj-Gopalganj'],
							['Ranaping-Gopalganj'],
							['Jainthapur-Jaintapur'],
							['Ichhamati-Jakiganj'],
							['Jakiganj-Jakiganj'],
							['Chatulbazar-Kanaighat'],
							['Gachbari-Kanaighat'],
							['Kanaighat-Kanaighat'],
							['Manikganj-Kanaighat'],
							['Kompanyganj-Kompanyganj'],
							['Birahimpur-Sylhet Sadar'],
							['Jalalabad-Sylhet Sadar'],
							['Jalalabad Cantoment-Sylhet Sadar'],
							['Kadamtali-Sylhet Sadar'],
							['Kamalbazer-Sylhet Sadar'],
							['Khadimnagar-Sylhet Sadar'],
							['Lalbazar-Sylhet Sadar'],
							['Mogla-Sylhet Sadar'],
							['Ranga Hajiganj-Sylhet Sadar'],
							['Shahajalal Science &-Sylhet Sadar'],
							['Silam-Sylhet Sadar'],
							['Sylhe Sadar-Sylhet Sadar'],
							['Sylhet Biman Bondar-Sylhet Sadar'],
							['Sylhet Cadet Col-Sylhet Sadar'],
							['Bangla Hili-Bangla Hili'],
							['Biral-Biral'],
							['Birampur-Birampur'],
							['Birganj-Birganj'],
							['Chrirbandar-Chrirbandar'],
							['Ranirbandar-Chrirbandar'],
							['Dinajpur Rajbari-Dinajpur Sadar'],
							['Dinajpur Sadar-Dinajpur Sadar'],
							['Khansama-Khansama'],
							['Pakarhat-Khansama'],
							['Maharajganj-Maharajganj'],
							['Daudpur-Nababganj'],
							['Gopalpur-Nababganj'],
							['Nababganj-Nababganj'],
							['Ghoraghat-Osmanpur'],
							['Osmanpur-Osmanpur'],
							['Parbatipur-Parbatipur'],
							['Phulbari-Phulbari'],
							['Setabganj-Setabganj'],
							['Bonarpara-Bonarpara'],
							['saghata-Bonarpara'],
							['Gaibandha Sadar-Gaibandha Sadar'],
							['Gobindhaganj-Gobindaganj'],
							['Mahimaganj-Gobindaganj'],
							['Palashbari-Palashbari'],
							['Bharatkhali-Phulchhari'],
							['Phulchhari-Phulchhari'],
							['Naldanga-Saadullapur'],
							['Saadullapur-Saadullapur'],
							['Bamandanga-Sundarganj'],
							['Sundarganj-Sundarganj'],
							['Bhurungamari-Bhurungamari'],
							['Chilmari-Chilmari'],
							['Jorgachh-Chilmari'],
							['Kurigram Sadar-Kurigram Sadar'],
							['Pandul-Kurigram Sadar'],
							['Phulbari-Kurigram Sadar'],
							['Nageshwar-Nageshwar'],
							['Nazimkhan-Rajarhat'],
							['Rajarhat-Rajarhat'],
							['Rajibpur-Rajibpur'],
							['Roumari-Roumari'],
							['Bazarhat-Ulipur'],
							['Ulipur-Ulipur'],
							['Aditmari-Aditmari'],
							['Hatibandha-Hatibandha'],
							['Kulaghat SO-Lalmonirhat Sadar'],
							['Lalmonirhat Sadar-Lalmonirhat Sadar'],
							['Moghalhat-Lalmonirhat Sadar'],
							['Baura-Patgram'],
							['Burimari-Patgram'],
							['Patgram-Patgram'],
							['Tushbhandar-Tushbhandar'],
							['Dimla-Dimla'],
							['Ghaga Kharibari-Dimla'],
							['Chilahati-Domar'],
							['Domar-Domar'],
							['Jaldhaka-Jaldhaka'],
							['Kishoriganj-Kishoriganj'],
							['Nilphamari Sadar-Nilphamari Sadar'],
							['Nilphamari Sugar Mil-Nilphamari Sadar'],
							['Syedpur-Syedpur'],
							['Syedpur Upashahar-Syedpur'],
							['Boda-Boda'],
							['Chotto Dab-Chotto Dab'],
							['Mirjapur-Chotto Dab'],
							['Dabiganj-Dabiganj'],
							['Panchagar Sadar-Panchagra Sadar'],
							['Tetulia-Tetulia'],
							['Badarganj-Badarganj'],
							['Shyampur-Badarganj'],
							['Gangachara-Gangachara'],
							['Haragachh-Kaunia'],
							['Kaunia-Kaunia'],
							['Mithapukur-Mithapukur'],
							['Pirgachha-Pirgachha'],
							['Alamnagar-Rangpur Sadar'],
							['Mahiganj-Rangpur Sadar'],
							['Rangpur Cadet Colleg-Rangpur Sadar'],
							['Rangpur Carmiecal Col-Rangpur Sadar'],
							['Rangpur Sadar-Rangpur Sadar'],
							['Rangpur Upa-Shahar-Rangpur Sadar'],
							['Taraganj-Taraganj'],
							['Baliadangi-Baliadangi'],
							['Lahiri-Baliadangi'],
							['Jibanpur-Jibanpur'],
							['Pirganj-Pirganj'],
							['Pirganj-Pirganj'],
							['Nekmarad-Rani Sankail'],
							['Rani Sankail-Rani Sankail'],
							['Ruhia-Thakurgaon Sadar'],
							['Shibganj-Thakurgaon Sadar'],
							['Thakurgaon Road-Thakurgaon Sadar'],
							['Thakurgaon Sadar-Thakurgaon Sadar'],

				];


protected $books = [

			['Holud Himu Kalo Rab','Humayun Ahmed'],
			['Kichu Shaisob','Humayun Ahmed'],
			['Megher Chaya','Humayun Ahmed'],
			['Chader Aloy Koyekjon Jubok','Humayun Ahmed'],
			['Ami E Misir Ali','Humayun Ahmed'],
			['Krisnopokkho','Humayun Ahmed'],
			['Brihonnola','Humayun Ahmed'],
			['Aj Himur Biye','Humayun Ahmed'],
			['Aynaghor','Humayun Ahmed'],
			['Tetul Bone Jochona','Humayun Ahmed'],
			['Se Ashe Dhire','Humayun Ahmed'],
			['Daruchini Dip','Humayun Ahmed'],
			['Amar Ache Jol','Humayun Ahmed'],
			['Ekjon Himu o Koyekti Jhin Jhin Poka','Humayun Ahmed'],
			['Andhakarer Gan','Humayun Ahmed'],
			['Achinpur','Humayun Ahmed'],
			['Sabai Geche Bone','Humayun Ahmed'],
			['Ural Pankhi','Humayun Ahmed'],
			['Voy','Humayun Ahmed'],
			['Debi','Humayun Ahmed'],
			['Moyurakkhi','Humayun Ahmed'],
			['Dui Duari','Humayun Ahmed'],
			['Neel Aparajita','Humayun Ahmed'],
			['Ebong Himu','Humayun Ahmed'],
			['Pakhi Amar Ekla Pakhi','Humayun Ahmed'],
			['Rupali Dip','Humayun Ahmed'],
			['Rodon Vora E Bosonto','Humayun Ahmed'],
			['Brishti Bilash','Humayun Ahmed'],
			['Darjar Opashe','Humayun Ahmed'],
			['Pufi by Humayun','Humayun Ahmed'],
			['Nabani','Humayun Ahmed'],
			['Himur Rupali Ratri','Humayun Ahmed'],
			['Angul Kata Jaglu','Humayun Ahmed'],
			['Kohen Kobi Kalidas','Humayun Ahmed'],
			['Himur Hate Koyekti Nil Podma','Humayun Ahmed'],
			['Badshah Namdar','Humayun Ahmed'],
			['Basor','Humayun Ahmed'],
			['Himu Mama','Humayun Ahmed'],
			['Bagh Bondhi Misir Ali','Humayun Ahmed'],
			['Himur Ditio Prohor','Humayun Ahmed'],
			['Amar Chelebela','Humayun Ahmed'],
			['Amar Priyo Voutik Golpo','Humayun Ahmed'],
			['Ami Ebong Amra ','Humayun Ahmed'],
			['Nishad','Humayun Ahmed'],
			['Tondra Bilash','Humayun Ahmed'],
			['Adbhut Sob Golpo','Humayun Ahmed'],
			['Aj Chitrar Biye','Humayun Ahmed'],
			['Akash Jora Megh','Humayun Ahmed'],
			['Chokkhe Amar Trishna','Humayun Ahmed'],
			['Jol Jochona','Humayun Ahmed'],
			['Kuhurani','Humayun Ahmed'],
			['Ball Point','Humayun Ahmed'],
			['Aj Ami Kothao Jabo Na','Humayun Ahmed'],
			['Ananto Nokkhotro Bithi','Humayun Ahmed'],
			['Asmanira Tin Bon','Humayun Ahmed'],
			['Amader Sada Bari','Humayun Ahmed'],
			['Ami Ebong Koyekti Projapoti','Humayun Ahmed'],
			['Amra Keu Basay Nei','Humayun Ahmed'],
			['Sajghor','Humayun Ahmed'],
			['Tooki Ebong Jha Er Pray Dussahosik Ovijan','Muhammad Zafar Iqbal'],
			['Mohakashe Mohatras','Muhammad Zafar Iqbal'],
			['Ekjon Oti Manobi','Muhammad Zafar Iqbal'],
			['Fobiayaner Jatri','Muhammad Zafar Iqbal'],
			['Neorone Abaro Onuranan','Muhammad Zafar Iqbal'],
			['Ami Topu','Muhammad Zafar Iqbal'],
			['Biggani Safdar Alir Moha Moha Abiskar','Muhammad Zafar Iqbal'],
			['Dipu Number 2','Muhammad Zafar Iqbal'],
			['Amra o Crab Nebula','Muhammad Zafar Iqbal'],
			['Eron','Muhammad Zafar Iqbal'],
			['1971 Prothom Porbo / ১৯৭১ প্রথম পর্ব','Abdur Rauf Chowdury'],
			['
50 Bisheshoggo Chikitshoker Mukhomukhi / ৫০ বিশেষজ্ঞ চিকিৎসকের মুখোমুখি','Dr. Shajal Ashfak']


];


	public function run()
	{
	//	Eloquent::unguard();


		$this->zilla();
		$this->place();
		$this->books();
		$this->user();

	}

	public function user()
	{
	echo 'User Generator turned on! \n';

		$faker = Faker\Factory::create();

		//echo $random_generator = $casus->getGenerator();

			for ($i=0; $i < 1000; $i++) {
				# code...
				$zilla =  rand(1,64);
				$place = rand(1,1349);

				DB::table('users_table')->insert([
				            'username' 		=> $faker->username,
				            'first_name' 	=> $faker->firstName,
				            'last_name' 	=> $faker->lastName,
										'phn_number' 	=> $faker->phoneNumber,
										'email'			 	=> $faker->email,
										'password'		=> md5('12345'),
										'library_name'=> $faker->company . ' ' . $faker->companySuffix,
										'zilla'				=> $zilla,
										'place'				=> $place,
										'address'			=> $faker->address
				]);

/*
//echo $faker->username;
//echo $faker->firstName;
//echo $faker->lastName;
//echo $faker->phoneNumber;
//echo $faker->email;
//echo $faker->company.' ' . $faker->companySuffix;
//echo $zilla;
//echo $place;
//echo $faker->address;
*/

			}
			echo 'User Generated.... \n';

	}

	public function books()
	{
		echo 'Book Generator turned on... \n';
			for ($i=0; $i < 60; $i++) {
				# code...

				foreach ($this->books as $value) {
					# code...
					$rand = rand(1,1000);

					DB::table('books')->insert([
					      	'book_name' 		=> $value[0],
									'writer_name'		=> $value[1],
									'shop_id'	 			=> $rand
					]);

				}

			}
		echo 'Book generated........ \n';

	}


	public function zilla()
	{
			echo 'Generating zilla.... \n';
			foreach ($this->districs as $value) {
				# code...
				DB::table('zilla')->insert([
				      	'zilla_name' => $value[0],
								'zilla_bn'	 => $value[1]
				]);

			}
			echo 'All zilla\'s are generated \n';
	}

	public function place()
	{
		echo 'Generating place... \n';

		foreach ($this->places as $value) {
			# code...
		$random = rand(1,64);

			DB::table('place')->insert([
							'zilla_id'	 => $random,
							'place_name' => $value[0]
			]);

		}
		echo 'Place generated... \n';
	}

}
